import React,{useEffect,useState} from 'react';
import {Alert,Button,Collapse,Input,Modal,Pagination,Select,Space,Table,Tag,Typography,message} from 'antd';
const apiUrl=(url)=>'/operations'+url;
const pct=v=>v==null?'不可计算':`${v.toFixed(2)}%`, pp=v=>v==null?'—':`${v>0?'+':''}${v.toFixed(2)} pp`,num=v=>v==null?'—':v.toLocaleString();
const coverage=r=>r.identityCoverage?`缺用户标识事件 ${num(r.identityCoverage.missingUserIdEvents)}`:r.sessionCoverage?`终态 ${num(r.sessionCoverage.terminalCount)} · 同日发起 ${num(r.sessionCoverage.startCount)} · 未知终态 ${num(r.sessionCoverage.unknownStatusCount)} · 缺连接ID ${num(r.sessionCoverage.missingConnectionIdEvents)} · 矛盾 ${num(r.sessionCoverage.contradictoryConnectionCount)}`:'—';
const reasonColumns=[{title:'类别',dataIndex:'category',width:150,render:v=><span style={{overflowWrap:'anywhere'}}>{v}</span>},{title:'错误码',dataIndex:'errorCode',width:170,render:v=><span style={{overflowWrap:'anywhere'}}>{v}</span>},{title:'消息',dataIndex:'message',render:v=><span style={{overflowWrap:'anywhere'}}>{v}</span>},{title:'事件数',dataIndex:'count',width:90,render:num},{title:'占 raw',dataIndex:'percent',width:90,render:v=>pct(v)}];
const topReasonColumns=reasonColumns.map(column=>column.dataIndex==='message'?{...column,render:v=><Typography.Text ellipsis={{tooltip:v}} style={{maxWidth:220}}>{v}</Typography.Text>}:column);
function FailureReasons({record}){const dist=record.failureReasonDistribution,top=record.failureReasonTop||[];if(!dist)return <span>暂无该指标失败原因</span>;const rest=Math.max(0,dist.tuples.length-top.length),available=dist.available!==false&&dist.status!=='unavailable';return <div data-testid="failure-reasons"><div style={{fontSize:12,lineHeight:1.45,marginBottom:6}}><div><b>错误日志分布（事件口径）</b> · raw event total {num(dist.rawTotal)}（百分比分母，all-source incl retries） · {available?(dist.source||'—'):'来源不可用 / 无观测'} · checkedAt {dist.checkedAt||'—'}</div><div>summary failure {num(dist.summaryFailureCount)}（request/final scope） · {dist.summarySource||'—'} · checkedAt {dist.summaryCheckedAt||'—'} · {available?<>差异（未对账）{num(dist.difference)}，口径不可直接比较</>:<>raw分母未知，不可比较/不可对账</>}</div></div>{top.length?<Table rowKey="id" size="small" pagination={false} dataSource={top} columns={topReasonColumns}/>:<Tag color={available?'default':'red'}>{record.failureReasonLabel||'未上报/未覆盖'}</Tag>}{rest>0&&<Collapse size="small" style={{marginTop:6}} items={[{key:'all',label:`另${rest}类，展开全部`,children:<Table rowKey="id" size="small" pagination={{pageSize:10,showSizeChanger:false}} dataSource={dist.tuples} columns={reasonColumns}/>}]}/>}</div>}
async function get(url,signal){const r=await fetch(apiUrl(url,location.pathname),{signal});const x=await r.json();if(!r.ok)throw new Error(x.message||x.error||'读取失败');return x}
// Counts remain source-specific; this is a native report, not an embedded app.
function Details({summary,group}){
 const [view,setView]=useState('affected'),[offset,setOffset]=useState(0),[data,setData]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[busy,setBusy]=useState(false);
 const query=new URLSearchParams({runId:summary.runId,date:group.date,category:group.category,view,offset,limit:20}).toString();
 useEffect(()=>{const c=new AbortController();setData(null);setError('');const t=setTimeout(()=>c.abort(),15000);get('/api/anomalies/details?'+query,c.signal).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message);else if(e.name==='AbortError')setError('读取超时，请重试')}).finally(()=>clearTimeout(t));return()=>{clearTimeout(t);c.abort()}},[query,retry]);
 const exportCsv=async()=>{setBusy(true);try{const r=await fetch(apiUrl('/api/anomalies/export?'+query,location.pathname));if(!r.ok)throw new Error('导出失败，请刷新结果');const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${group.date}-${group.category}-${view}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){message.error(e.message)}finally{setBusy(false)}};
 return <div data-testid="anomaly-details"><p>{group.semantics}</p><Space wrap style={{marginBottom:12}}><Select aria-label="异常明细范围" value={view} style={{width:210}} options={[{value:'affected',label:'命中默认筛选的全部项目'},{value:'all',label:'全部项目（含未命中/缺数）'},{value:'missing',label:'不可计算/缺数项目'}]} onChange={v=>{setView(v);setOffset(0)}}/><Button loading={busy} onClick={exportCsv}>导出当前筛选全部 CSV</Button><span>共 {data?.total??'—'} 项（不是 Top 截取）</span></Space>{error&&<Alert type="error" message={error} action={<Button onClick={()=>setRetry(x=>x+1)}>重试</Button>}/>}
 <Table rowKey="id" size="small" loading={!data&&!error} pagination={false} scroll={{x:2050}} dataSource={data?.records||[]} columns={[
 {title:'项目 / 应用 / 包名',width:260,render:(_,r)=><><b>{r.projectCode} · {r.appName}</b><div style={{wordBreak:'break-all'}}>{r.packageName||'包名未映射'}</div>{!r.registered&&<Tag>注册表外观测</Tag>}</>},
 {title:'失败原因',width:650,render:(_,r)=><FailureReasons record={r}/>} ,
 {title:'当前',dataIndex:'current',render:pct},{title:'前日',dataIndex:'baseline',render:pct},{title:'变化',dataIndex:'deltaPp',render:pp},
 {title:'当前分子 / 分母',render:(_,r)=>`${num(r.numerator)} / ${num(r.denominator)}`},{title:'前日分子 / 分母',render:(_,r)=>`${num(r.baselineNumerator)} / ${num(r.baselineDenominator)}`},
 {title:'失败 / 差额 / 错误量',dataIndex:'failureCount',render:num},{title:'筛选依据 / 样本',width:280,render:(_,r)=><><Tag color={r.candidate?'orange':'default'}>{r.status}</Tag><div>{r.reason}</div></>},
 {title:'身份 / 终态覆盖',width:260,render:(_,r)=>coverage(r)},
 {title:'日期 / 来源',width:220,render:(_,r)=><small>{r.date}<br/>{r.source}</small>},
 ]} expandable={{expandedRowRender:r=><div><p>{r.semantics}</p>{r.sourceReconciliation&&<Alert type={r.sourceReconciliation.status==='unavailable'?'error':'warning'} message={r.sourceReconciliation.status==='unavailable'?'raw来源不可用，无法对账':`来源未对账：汇总加载失败 ${num(r.sourceReconciliation.summaryLoadFailed)} / raw加载失败 ${num(r.sourceReconciliation.rawLoadFailed)} / 差异 ${num(r.sourceReconciliation.difference)}`} description={<>{r.sourceReconciliation.notice}<br/>{r.sourceReconciliation.summarySource} / {r.sourceReconciliation.rawSource||'—'}</>}/>} {r.identityCoverage&&<p>身份覆盖：{coverage(r)}</p>}{r.sessionCoverage&&<p>连接终态覆盖：{coverage(r)}；同日未匹配发起 {num(r.sessionCoverage.sameDayMissingTerminalCount)}，同日未匹配终态 {num(r.sessionCoverage.sameDayUnmatchedTerminalCount)}。这是日内观察，不代表全局未完成或失败。</p>}{r.phaseCoverage&&<p>TCP阶段覆盖：{JSON.stringify(r.phaseCoverage)}（unknown / not_executed 不进入分母；主路径及广告路径合计，不是广告专属握手率）</p>}{r.unresolvedOrCountDifference!=null&&<p>同日未匹配差额：{r.unresolvedOrCountDifference}（不归为失败）</p>}<p>实际错误消息 / 探测目标明细（不是推断根因）：</p>{r.breakdown.length?<Table rowKey={(_,i)=>i} size="small" pagination={{pageSize:10,showSizeChanger:false}} dataSource={r.breakdown} columns={[{title:'错误码',dataIndex:'errorCode',width:180},{title:'原始消息',dataIndex:'message',render:v=><span style={{overflowWrap:'anywhere'}}>{v}</span>},{title:'事件数',dataIndex:'count',width:100}]}/>:<p>本指标无逐错误消息；请在高频错误类别查看。</p>}</div>}}/>
 <Pagination style={{marginTop:12}} current={offset/20+1} pageSize={20} total={data?.total||0} showSizeChanger={false} onChange={p=>setOffset((p-1)*20)}/></div>
}
export function DailyAnomalies({ready,authError,onRetry}){
 const [summary,setSummary]=useState(null),[date,setDate]=useState(''),[error,setError]=useState(''),[retry,setRetry]=useState(0),[selected,setSelected]=useState(null);
 useEffect(()=>{if(!ready)return;const c=new AbortController();const t=setTimeout(()=>c.abort(),15000);get('/api/anomalies/summary',c.signal).then(x=>{setSummary(x.anomalies);setDate(old=>x.anomalies.dates.includes(old)?old:x.anomalies.dates.at(-1));setError('')}).catch(e=>setError(e.name==='AbortError'?'异常摘要读取超时':e.message)).finally(()=>clearTimeout(t));return()=>{clearTimeout(t);c.abort()}},[retry,ready]);
 const rows=(summary?.groups||[]).filter(g=>g.date===date).sort((a,b)=>b.failureCount-a.failureCount);
 return <main data-testid="daily-anomalies-page" style={{padding:16}}><div className="page-title"><div><Typography.Title level={3}>每日异常</Typography.Title><Typography.Text type="secondary">先看问题影响哪些包，再看每包指标和实际错误。缺数不当正常。</Typography.Text></div></div>
 <Space wrap style={{marginBottom:12}}><Select aria-label="异常日期" style={{width:180}} value={date||undefined} options={(summary?.dates||[]).map(value=>({value,label:value+' 完整自然日'}))} onChange={setDate}/><Button onClick={()=>{setSelected(null);setRetry(x=>x+1)}}>刷新已汇总结果</Button><span>注册 {summary?.registeredProjects??'—'} 项目 · 观测范围 {summary?.projectCount??'—'} 项目 · 映射去重 {summary?.packageCount??'—'} 包 · 包名未映射 {summary?.unmappedProjects??'—'} 项目</span></Space>
 {(error||authError)&&<Alert type="error" showIcon message={error||authError} action={<Button onClick={onRetry}>重试认证</Button>}/>}<Alert type={summary?.stale?'error':'info'} showIcon message={summary?.stale?'结果陈旧或本轮失败；请勿视为当前结论':'后台每小时预汇总 · 北京时间09:00复查晚到数据'} description={<><div>检查时间：{summary?.checkedAt||'—'} · 下次计划：{summary?.nextCheckAt||'—'} · {summary?.checkKind||'尚未采集'}</div><div>{summary?.upstreamFinality||'无项目级最终完整性水位'}。全项目范围=真实注册表 + 未注册观测（标注），并非只看有数据的包。</div></>}/>
 <Collapse style={{margin:'12px 0'}} items={[{key:'rules',label:'查看默认筛选口径（异常候选，非批准SLA）',children:<><p>分母≥{summary?.rules?.minSample??100}；TCP明确握手低于{summary?.rules?.tcpFloor??90}%或下降≥{summary?.rules?.dropPp??5}pp，广告加载终态低于{summary?.rules?.adLoadFloor??80}%或下降≥{summary?.rules?.dropPp??5}pp；广告浏览者比例、展示事件比及VPN比率无绝对目标，仅在两日样本均达标、下降≥{summary?.rules?.dropPp??5}pp且相对下降≥{summary?.rules?.relativeDropPct??20}%时列候选；错误事件≥{summary?.rules?.errorMinCount??100}且占全部加载失败≥{summary?.rules?.errorShareFloor??10}%。数据矛盾不受最小样本限制，单列为 data_anomaly。</p><p>广告浏览者比例=项目×北京时间自然日 ad_impression 去重 my_user_id / app_foreground 去重 my_user_id，不跨版本或国家求和。VPN连接成功率（终态）=结果日成功终态去重 connection_id / 结果日全部终态去重 connection_id；同日成功/发起只是非关联观察，跨日可超过100%，不等于失败率；connection_id、vpn_session_id 与用户转化不可混用。无基线不生成变化，异常基线排除普通下降比较；小样本不判健康。以上是临时工作筛选，不是统计显著性检验或已批准业务SLA。</p></>}]} />
 <Table data-testid="anomaly-groups" rowKey="category" size="small" loading={!summary&&!error&&!authError} pagination={false} scroll={{x:1200}} dataSource={rows} columns={[
 {title:'问题类别 / 指标',dataIndex:'label',width:300,render:(v,r)=><Button type="link" style={{whiteSpace:'normal',height:'auto',textAlign:'left'}} onClick={()=>setSelected({summary,group:r})}>{v}</Button>},
 {title:'受影响项目',dataIndex:'affectedProjects'},{title:'实际去重包数',dataIndex:'affectedPackages'},{title:'命中但包未映射',dataIndex:'unmappedAffectedProjects'},
 {title:'可计算 / 缺数',render:(_,r)=>`${r.coveredProjects} / ${r.missingProjects}`},{title:'小样本',dataIndex:'smallSampleProjects'},
 {title:'失败 / 差额 / 错误量',dataIndex:'failureCount',render:num},{title:'最大下降 / 中位变化',render:(_,r)=>`${pp(r.maxDropPp)} / ${pp(r.medianDeltaPp)}`},
 {title:'',render:(_,r)=><Button onClick={()=>setSelected({summary,group:r})}>查看全部项目</Button>}
 ]}/><p className="muted">失败事件、阶段差额与展示差额按各自口径展示；不合并成事故总数。TCP只统计明确阶段，未知覆盖必须展开查看。</p>
 <Modal width="95%" open={!!selected} footer={null} destroyOnHidden title={selected?`${selected.group.date} · ${selected.group.label}`:''} onCancel={()=>setSelected(null)}>{selected&&<Details key={selected.summary.runId+selected.group.date+selected.group.category} summary={selected.summary} group={selected.group}/>}</Modal>
 </main>
}
