import React,{useEffect,useRef,useState} from 'react';
import {Alert,Button,Input,Select,Space,Table,Typography,message} from 'antd';
const DIMENSIONS=[['project','项目'],['anomaly','异常原因'],['error','错误原因'],['date','日期'],['developer','开发'],['version','版本']];
const FIELDS=[['appName','应用'],['packageName','包名'],['failureReasons','失败原因（观测）'],['version','版本'],['projectCount','项目数'],['packageCount','包数'],['current','当日率'],['baseline','昨日率'],['deltaPp','环比变化(pp)'],['relativeChangePct','相对环比(%)'],['numerator','当日分子'],['denominator','当日分母'],['baselineNumerator','昨日分子'],['baselineDenominator','昨日分母'],['failureCount','指标失败次数'],['errorCount','当日错误事件数'],['errorShare','当日错误占比'],['baselineErrorCount','昨日错误事件数'],['baselineErrorShare','昨日错误占比'],['errorDeltaCount','错误事件变化'],['errorRelativeChangePct','错误事件环比(%)']];
const DEFAULT_FIELDS=['appName','packageName','failureReasons','current','baseline','deltaPp','relativeChangePct','numerator','denominator','errorCount','errorShare'];
const defaults=()=>({dimensions:['project','anomaly'],view:'affected',startDate:'',endDate:'',projectCode:'',category:'',errorId:'',developerId:'',appName:'',packageName:'',appVersion:'',errorCategory:'',errorCode:'',errorMessage:'',sortBy:'errorCount',sortDirection:'desc'});
const display=v=>v==null?'不可用':typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:2}):v;
const percent=v=>v==null?'不适用 / 不可计算':`${v.toFixed(2)}%`;
const queryString=args=>new URLSearchParams(Object.entries(args).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>[k,Array.isArray(v)?v.join(','):String(v)])).toString();
async function responseError(r){let payload={};try{payload=await r.json()}catch{}return Object.assign(new Error(payload.message||payload.error||`读取失败 HTTP ${r.status}`),{status:r.status})}
export function DailyAnomalies({ready,authError,onRetry,onAuthRevoked}){
 const [draft,setDraft]=useState(defaults),[fields,setFields]=useState(DEFAULT_FIELDS),[request,setRequest]=useState({...defaults(),offset:0,limit:30,serial:0}),[snapshot,setSnapshot]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[exporting,setExporting]=useState(false);
 const generation=useRef(0),controllers=useRef(new Set()),mounted=useRef(true);
 const abortAll=()=>{generation.current++;for(const c of controllers.current)c.abort();controllers.current.clear()};
 const clear=reason=>{abortAll();setSnapshot(null);setDraft(defaults());setError(reason?.message||'认证失效，数据已清除');setLoading(false);setExporting(false)};
 const revoke=reason=>{clear(reason);onAuthRevoked?.(reason)};
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;abortAll()}},[]);
 useEffect(()=>{if([401,403].includes(authError?.status))clear(authError)},[authError]);
 useEffect(()=>{
  if(!ready)return;
  abortAll();setExporting(false);const epoch=generation.current,c=new AbortController();controllers.current.add(c);setLoading(true);setError('');
  const timeout=setTimeout(()=>c.abort('timeout'),15000);const {serial,...filters}=request;
  fetch('/operations/api/anomalies/details?'+queryString({report:'overall',...filters}),{signal:c.signal}).then(async r=>{if(!r.ok)throw await responseError(r);return r.json()}).then(data=>{
   if(!mounted.current||epoch!==generation.current||c.signal.aborted)return;
   if(!Array.isArray(data.records)||!data.options||!Array.isArray(data.dimensions))throw new Error('报表返回结构不可用');
   setSnapshot({data,request,filters:{...filters,runId:data.runId,startDate:data.startDate,endDate:data.endDate}});
   setDraft(old=>({...old,startDate:old.startDate||data.startDate,endDate:old.endDate||data.endDate}));
  }).catch(e=>{if(!mounted.current||epoch!==generation.current)return;if([401,403].includes(e.status))return revoke(e);if(!c.signal.aborted||c.signal.reason==='timeout')setError(c.signal.reason==='timeout'?'读取超时，保留上次结果':e.message)}).finally(()=>{clearTimeout(timeout);controllers.current.delete(c);if(mounted.current&&epoch===generation.current)setLoading(false)});
  return()=>{clearTimeout(timeout);c.abort();controllers.current.delete(c)};
 },[ready,request]);
 const data=snapshot?.data,options=data?.options||{},appliedDimensions=data?.dimensions||['project','anomaly'],matches=snapshot?.request===request,canExport=ready&&matches&&!loading&&!authError;
 const update=(key,value)=>setDraft(old=>({...old,[key]:value||''}));
 const query=()=>setRequest({...draft,runId:data?.runId,offset:0,limit:30,serial:request.serial+1});
 const reset=()=>{setDraft(defaults());setFields(DEFAULT_FIELDS);setRequest({...defaults(),offset:0,limit:30,serial:request.serial+1})};
 const exportCsv=async()=>{
  if(!canExport)return;
  const epoch=generation.current,c=new AbortController();controllers.current.add(c);setExporting(true);
  try{const r=await fetch('/operations/api/anomalies/export?'+queryString({report:'overall',...snapshot.filters}),{signal:c.signal});if(!r.ok)throw await responseError(r);const blob=await r.blob();if(!mounted.current||epoch!==generation.current||c.signal.aborted)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`daily-anomalies-${data.startDate}-${data.endDate}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){if([401,403].includes(e.status))revoke(e);else if(!c.signal.aborted)message.error(e.message)}finally{controllers.current.delete(c);if(mounted.current&&epoch===generation.current)setExporting(false)}
 };
 const columns=[...appliedDimensions.flatMap(key=>key==='error'?[{title:'错误 category',dataIndex:'errorCategory',width:160},{title:'错误 code',dataIndex:'errorCode',width:150},{title:'错误 message（已脱敏）',dataIndex:'errorMessage',width:260}]:[{title:DIMENSIONS.find(([id])=>id===key)?.[1]||key,dataIndex:key,width:key==='anomaly'?240:160}]),
  {title:'异常指标 / 口径',dataIndex:'metric',width:200},{title:'日期 / 前一日',width:180,render:(_,r)=><small>{r.statDates?.join(' / ')}<br/>昨日 {r.baselineDate}</small>},
  ...FIELDS.filter(([key])=>fields.includes(key)&&!(key==='version'&&appliedDimensions.includes('version'))).map(([key,title])=>({title,dataIndex:key,width:key==='failureReasons'?410:140,sorter:['projectCount','packageCount','current','baseline','deltaPp','failureCount','errorCount','errorShare','relativeChangePct','errorRelativeChangePct','version'].includes(key),render:(v,r)=>key==='failureReasons'?(r.failureReasons?.length?<div>{r.failureReasons.slice(0,3).map(t=><div key={t.id}><b>{t.category} / {t.errorCode}</b><Typography.Paragraph ellipsis={{rows:2,expandable:true,symbol:'完整消息'}} style={{margin:0}}>{t.message}</Typography.Paragraph><small>事件 {display(t.count)} · 占raw {percent(t.percent)}</small></div>)}{r.failureReasons.length>3&&<small>另 {r.failureReasons.length-3} 类，展开行查看全部或勾选错误原因维度</small>}</div>:<span>错误来源/观测不可用或已覆盖0事件（见raw总量）</span>):key==='version'?(v||r.versionCoverage):['current','baseline','errorShare','baselineErrorShare','relativeChangePct','errorRelativeChangePct'].includes(key)?percent(v):key==='deltaPp'?(v==null?'不可比':`${v>0?'+':''}${v.toFixed(2)} pp`):display(v)})),
  {title:'触发依据 / 样本',dataIndex:'reason',width:280,render:v=><Typography.Paragraph ellipsis={{rows:3,expandable:true,symbol:'全部依据'}} style={{margin:0}}>{v}</Typography.Paragraph>},
  {title:'覆盖 / 来源新鲜度',width:260,render:(_,r)=><small>{r.coverage}<br/>{r.source}<br/>检查 {r.checkedAt}{data?.stale?'（陈旧）':''}<br/>错误检查 {r.errorCheckedAt||'不可用'}</small>},
  {title:'错误事件 / request失败对账',width:250,render:(_,r)=><small>raw总量 {display(r.rawTotal)}（占比分母，含重试）<br/>summary失败 {display(r.summaryFailures)}（request去重口径）<br/>未对账差异 {display(r.difference)}<br/>{r.sourceStatus}</small>},
 ];
 return <main data-testid="daily-anomalies-page" style={{padding:16}}><div className="page-title"><Typography.Title level={3}>每日异常</Typography.Title></div><div className="vpn-overall-report ad-overall-report">
  <section className="surface matrix-overall-config" data-testid="daily-overall-config">
   <div className="overall-config-row dimension-row"><span className="overall-config-label">维度</span>{DIMENSIONS.map(([key,label])=><label className={`overall-chip ${draft.dimensions.includes(key)?'active':''}`} key={key}><input type="checkbox" aria-label={`维度-${label}`} checked={draft.dimensions.includes(key)} disabled={(draft.dimensions.length===1&&draft.dimensions.includes(key))||(key==='version'&&!options.versionSupported)} onChange={()=>setDraft(old=>({...old,dimensions:old.dimensions.includes(key)?old.dimensions.filter(x=>x!==key):[...old.dimensions,key]}))}/><span>{label}</span></label>)}</div>
   <div className="overall-config-row metric-row"><span className="overall-config-label">统计字段</span>{FIELDS.map(([key,label])=><label className={`overall-chip ${fields.includes(key)?'active':''}`} key={key}><input type="checkbox" aria-label={`显示-${label}`} checked={fields.includes(key)} onChange={()=>setFields(old=>old.includes(key)?old.filter(x=>x!==key):[...old,key])}/><span>{label}</span></label>)}</div>
   <div className="overall-filter-row"><label className="overall-filter-item"><span>已采集日期：</span><Select aria-label="开始日期" style={{width:145}} value={draft.startDate||undefined} options={(options.dates||[]).map(value=>({value,label:value}))} onChange={v=>setDraft(old=>({...old,startDate:v,endDate:old.endDate<v?v:old.endDate}))}/><span>→</span><Select aria-label="结束日期" style={{width:145}} value={draft.endDate||undefined} options={(options.dates||[]).filter(v=>!draft.startDate||v>=draft.startDate).map(value=>({value,label:value}))} onChange={v=>update('endDate',v)}/></label>
    {[['projectCode','项目',options.projects],['appName','应用',options.apps],['packageName','包名',options.packages],['category','异常原因',options.anomalies],['errorCategory','错误类别',options.errorCategories],['errorCode','错误码',options.errorCodes],['errorId','错误原因',options.errors],['appVersion','版本',options.versions],['developerId','开发',options.developers]].map(([key,label,items])=><label className="overall-filter-item" key={key}><span>{label}：</span><Select aria-label={`${label}筛选`} style={{width:220}} allowClear showSearch optionFilterProp="label" disabled={key==='appVersion'&&!options.versionSupported} placeholder={key==='appVersion'&&!options.versionSupported?'历史结果无版本粒度':'全部'} value={draft[key]||undefined} options={items||[]} onChange={v=>update(key,v)}/></label>)}
    <label className="overall-filter-item"><span>错误消息：</span><Input aria-label="错误消息关键词" placeholder="已脱敏消息关键词" maxLength={200} style={{width:220}} value={draft.errorMessage} onChange={e=>update('errorMessage',e.target.value)}/></label>
    <label className="overall-filter-item"><span>范围：</span><Select aria-label="异常范围" style={{width:190}} value={draft.view} options={[{value:'affected',label:'命中异常筛选'},{value:'all',label:'全部（含缺数）'},{value:'missing',label:'不可计算 / 缺数'}]} onChange={v=>update('view',v)}/></label>
   </div>
   <div className="overall-action-row"><span className="muted">异常原因＝指标触发依据；错误原因＝真实观测 category/code/message，非已验证根因。</span><Space><Button disabled={!canExport} loading={exporting} onClick={exportCsv}>导出 CSV</Button><Button onClick={reset}>重置</Button><Button type="primary" onClick={query} disabled={!ready}>查询</Button></Space></div>
  </section>
  <section className="surface overall-result-card" data-testid="daily-overall-results">
   <div className="overall-result-tools"><strong>每日异常 Overall · {data?.total??'—'} 组</strong><span data-testid="overall-applied">{data?`${data.startDate} → ${data.endDate} · ${appliedDimensions.map(d=>DIMENSIONS.find(([id])=>id===d)?.[1]).join(' × ')} · ${snapshot.filters.projectCode||'全部项目'} · ${snapshot.filters.developerId||'全部开发'} · 范围 ${data.view}`:'等待已采集结果'}{snapshot&&!matches?'；保留上次成功条件，当前请求未应用':''}</span></div>
   {(error||authError)&&<Alert type="error" title={error||authError?.message||'采集状态暂不可读取'} action={<Button onClick={()=>ready?setRequest({...request,serial:request.serial+1}):onRetry?.()}>重试</Button>}/>}
   <Table data-testid="anomaly-groups" rowKey="id" size="small" loading={loading||(!data&&!error&&!authError)} columns={columns} dataSource={data?.records||[]} scroll={{x:'max-content'}} pagination={{current:Math.floor((data?.offset||0)/30)+1,pageSize:30,total:data?.total||0,showSizeChanger:false}} onChange={(page,_,sorter)=>{const next=sorter.field?{sortBy:sorter.field,sortDirection:sorter.order==='ascend'?'asc':'desc'}:{};setRequest({...snapshot?.filters,...next,dimensions:appliedDimensions,offset:(page.current-1)*30,limit:30,serial:request.serial+1})}} expandable={{expandedRowRender:r=><div><p>{r.semantics}</p><p>受影响项目 / 包（去重）：{r.packages.join('；')}</p><p>{r.reason}</p><p>前日分子 / 分母：{display(r.baselineNumerator)} / {display(r.baselineDenominator)}；{r.versionCoverage}</p><p>默认候选筛选（非SLA）：分母≥{r.rules?.minSample}；TCP低于{r.rules?.tcpFloor}%、广告加载低于{r.rules?.adLoadFloor}%或下降≥{r.rules?.dropPp}pp；无绝对目标的指标需相对下降≥{r.rules?.relativeDropPct}%；错误事件≥{r.rules?.errorMinCount}且占raw≥{r.rules?.errorShareFloor}%。小样本/缺数不判健康。</p><Table size="small" rowKey="id" dataSource={r.failureReasons||[]} pagination={{pageSize:10}} columns={[{title:'类别',dataIndex:'category'},{title:'错误码',dataIndex:'errorCode'},{title:'完整消息（已脱敏）',dataIndex:'message'},{title:'事件数',dataIndex:'count'},{title:'占raw',dataIndex:'percent',render:percent}]}/></div>}}/>
   <div className="matrix-footnote">{data?.notice||'按后台已采集全量明细聚合，分页、排序和CSV同一筛选。'} 当日＝行统计日期，昨日＝该日期前一天；跨日为项目日口径，非跨日独立UV。不同指标保持独立行；比例按同口径分子合计/分母合计。基线0时相对环比不可用。跨App UV非独立用户；错误来源缺失显示不可用，不补零。点击行首展开受影响包。</div>
  </section>
 </div></main>
}
