import React,{useEffect,useRef,useState} from 'react';
import {Alert,Button,Collapse,Input,Modal,Pagination,Select,Space,Table,Tag,Typography,message} from 'antd';
const apiUrl=(url)=>'/operations'+url;
const pct=v=>v==null?'不可计算':`${v.toFixed(2)}%`, pp=v=>v==null?'—':`${v>0?'+':''}${v.toFixed(2)} pp`,num=v=>v==null?'—':v.toLocaleString();
const coverage=r=>r.identityCoverage?`缺用户标识事件 ${num(r.identityCoverage.missingUserIdEvents)}`:r.sessionCoverage?`终态 ${num(r.sessionCoverage.terminalCount)} · 同日发起 ${num(r.sessionCoverage.startCount)} · 未知终态 ${num(r.sessionCoverage.unknownStatusCount)} · 缺连接ID ${num(r.sessionCoverage.missingConnectionIdEvents)} · 矛盾 ${num(r.sessionCoverage.contradictoryConnectionCount)}`:'—';
const reasonColumns=[{title:'类别',dataIndex:'category',width:150,render:v=><span style={{overflowWrap:'anywhere'}}>{v}</span>},{title:'错误码',dataIndex:'errorCode',width:170,render:v=><span style={{overflowWrap:'anywhere'}}>{v}</span>},{title:'消息',dataIndex:'message',render:v=><span style={{overflowWrap:'anywhere'}}>{v}</span>},{title:'事件数',dataIndex:'count',width:90,render:num},{title:'占 raw',dataIndex:'percent',width:90,render:v=>pct(v)}];
const topReasonColumns=reasonColumns.map(column=>column.dataIndex==='message'?{...column,render:v=><Typography.Text ellipsis={{tooltip:v}} style={{maxWidth:220}}>{v}</Typography.Text>}:column);
function FailureReasons({record}){const dist=record.failureReasonDistribution,top=record.failureReasonTop||[];if(!dist)return <span>暂无该指标失败原因</span>;const rest=Math.max(0,dist.tuples.length-top.length),available=dist.available!==false&&dist.status!=='unavailable';return <div data-testid="failure-reasons"><div style={{fontSize:12,lineHeight:1.45,marginBottom:6}}><div><b>错误日志分布（事件口径）</b> · raw event total {num(dist.rawTotal)}（百分比分母，all-source incl retries） · {available?(dist.source||'—'):'来源不可用 / 无观测'} · checkedAt {dist.checkedAt||'—'}</div><div>summary failure {num(dist.summaryFailureCount)}（request/final scope） · {dist.summarySource||'—'} · checkedAt {dist.summaryCheckedAt||'—'} · {available?<>差异（未对账）{num(dist.difference)}，口径不可直接比较</>:<>raw分母未知，不可比较/不可对账</>}</div></div>{top.length?<Table rowKey="id" size="small" pagination={false} dataSource={top} columns={topReasonColumns}/>:<Tag color={available?'default':'red'}>{record.failureReasonLabel||'未上报/未覆盖'}</Tag>}{rest>0&&<Collapse size="small" style={{marginTop:6}} items={[{key:'all',label:`另${rest}类，展开全部`,children:<Table rowKey="id" size="small" pagination={{pageSize:10,showSizeChanger:false}} dataSource={dist.tuples} columns={reasonColumns}/>}]}/>}</div>}
async function get(url,signal){const r=await fetch(apiUrl(url,location.pathname),{signal});let x={};try{x=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(x.message||x.error||`读取失败 HTTP ${r.status}`),{status:r.status,code:x.error});return x}
// Counts remain source-specific; this is a native report, not an embedded app.
function Details({summary,group,developerId,onAuthRevoked,trackController,currentGeneration}){
 const [view,setView]=useState('affected'),[offset,setOffset]=useState(0),[snapshot,setSnapshot]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[busy,setBusy]=useState(false),exportControllers=useRef(new Set()),mounted=useRef(true);
 const query=new URLSearchParams({runId:summary.runId,date:group.date,category:group.category,view,offset,limit:20,...(developerId?{developerId}:{})}).toString();
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;for(const controller of exportControllers.current)controller.abort('closed');exportControllers.current.clear()}},[]);
 useEffect(()=>{const c=new AbortController(),generation=currentGeneration();let active=true;const untrack=trackController(c);setError('');const t=setTimeout(()=>c.abort('timeout'),15000);get('/api/anomalies/details?'+query,c.signal).then(x=>{if(active&&generation===currentGeneration())setSnapshot({data:x,query,view,offset,checkedAt:x.checkedAt||summary.checkedAt||'—'})}).catch(e=>{if(!active||generation!==currentGeneration()||['revoked','obsolete'].includes(c.signal.reason))return;if([401,403].includes(e.status))return onAuthRevoked(e);setError(c.signal.reason==='timeout'?'读取超时，请重试':e.message)}).finally(()=>{clearTimeout(t);untrack()});return()=>{active=false;clearTimeout(t);untrack();c.abort('obsolete')}},[query,retry]);
 const matchesRequest=snapshot?.query===query,data=snapshot?.data;
 const exportCsv=async()=>{if(!matchesRequest)return;const c=new AbortController(),generation=currentGeneration(),untrack=trackController(c);exportControllers.current.add(c);setBusy(true);try{const r=await fetch(apiUrl('/api/anomalies/export?'+snapshot.query,location.pathname),{signal:c.signal});if(!r.ok){let payload={};try{payload=await r.json()}catch{}throw Object.assign(new Error(payload.message||payload.error||'导出失败，请刷新结果'),{status:r.status})}const blob=await r.blob();if(!mounted.current||generation!==currentGeneration()||c.signal.aborted)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${group.date}-${group.category}-${snapshot.view}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){if([401,403].includes(e.status))onAuthRevoked(e);else if(!c.signal.aborted)message.error(e.message)}finally{exportControllers.current.delete(c);untrack();if(mounted.current)setBusy(false)}};
 return <div data-testid="anomaly-details"><p>{group.semantics}</p><Space wrap style={{marginBottom:12}}><Select aria-label="异常明细范围" value={view} style={{width:210}} options={[{value:'affected',label:'命中默认筛选的全部项目'},{value:'all',label:'全部项目（含未命中/缺数）'},{value:'missing',label:'不可计算/缺数项目'}]} onChange={v=>{setView(v);setOffset(0)}}/><Button loading={busy} disabled={!matchesRequest} onClick={exportCsv}>导出当前筛选全部 CSV</Button><span>共 {data?.total??'—'} 项（不是 Top 截取）</span></Space>{snapshot&&<div data-testid="details-provenance">已显示：范围 {snapshot.view} · 第 {snapshot.offset/20+1} 页 · 检查时间 {snapshot.checkedAt}{!matchesRequest&&'；当前请求尚未应用，导出已禁用'}</div>}{error&&<Alert type="error" message={matchesRequest?error:`${error}；保留上次成功明细`} action={<Button onClick={()=>setRetry(x=>x+1)}>重试读取</Button>}/>}
 <Table rowKey="id" size="small" loading={!data&&!error} pagination={false} scroll={{x:2050}} dataSource={data?.records||[]} columns={[
 {title:'项目 / 应用 / 包名',width:260,render:(_,r)=><><b>{r.projectCode} · {r.appName}</b><div style={{wordBreak:'break-all'}}>{r.packageName||'包名未映射'}</div><div>{(r.developers||[]).map(d=><Tag key={d.id}>{d.name} · {d.id}</Tag>)}</div>{!r.registered&&<Tag>注册表外观测</Tag>}</>},
 {title:'失败原因',width:650,render:(_,r)=><FailureReasons record={r}/>} ,
 {title:'当前',dataIndex:'current',render:pct},{title:'前日',dataIndex:'baseline',render:pct},{title:'变化',dataIndex:'deltaPp',render:pp},
 {title:'当前分子 / 分母',render:(_,r)=>`${num(r.numerator)} / ${num(r.denominator)}`},{title:'前日分子 / 分母',render:(_,r)=>`${num(r.baselineNumerator)} / ${num(r.baselineDenominator)}`},
 {title:'失败 / 差额 / 错误量',dataIndex:'failureCount',render:num},{title:'筛选依据 / 样本',width:280,render:(_,r)=><><Tag color={r.candidate?'orange':'default'}>{r.status}</Tag><div>{r.reason}</div></>},
 {title:'身份 / 终态覆盖',width:260,render:(_,r)=>coverage(r)},
 {title:'日期 / 来源',width:220,render:(_,r)=><small>{r.date}<br/>{r.source}</small>},
 ]} expandable={{expandedRowRender:r=><div><p>{r.semantics}</p>{r.sourceReconciliation&&<Alert type={r.sourceReconciliation.status==='unavailable'?'error':'warning'} message={r.sourceReconciliation.status==='unavailable'?'raw来源不可用，无法对账':`来源未对账：汇总加载失败 ${num(r.sourceReconciliation.summaryLoadFailed)} / raw加载失败 ${num(r.sourceReconciliation.rawLoadFailed)} / 差异 ${num(r.sourceReconciliation.difference)}`} description={<>{r.sourceReconciliation.notice}<br/>{r.sourceReconciliation.summarySource} / {r.sourceReconciliation.rawSource||'—'}</>}/>} {r.identityCoverage&&<p>身份覆盖：{coverage(r)}</p>}{r.sessionCoverage&&<p>连接终态覆盖：{coverage(r)}；同日未匹配发起 {num(r.sessionCoverage.sameDayMissingTerminalCount)}，同日未匹配终态 {num(r.sessionCoverage.sameDayUnmatchedTerminalCount)}。这是日内观察，不代表全局未完成或失败。</p>}{r.phaseCoverage&&<p>TCP阶段覆盖：{JSON.stringify(r.phaseCoverage)}（unknown / not_executed 不进入分母；主路径及广告路径合计，不是广告专属握手率）</p>}{r.unresolvedOrCountDifference!=null&&<p>同日未匹配差额：{r.unresolvedOrCountDifference}（不归为失败）</p>}<p>实际错误消息 / 探测目标明细（不是推断根因）：</p>{r.breakdown.length?<Table rowKey={(_,i)=>i} size="small" pagination={{pageSize:10,showSizeChanger:false}} dataSource={r.breakdown} columns={[{title:'错误码',dataIndex:'errorCode',width:180},{title:'原始消息',dataIndex:'message',render:v=><span style={{overflowWrap:'anywhere'}}>{v}</span>},{title:'事件数',dataIndex:'count',width:100}]}/>:<p>本指标无逐错误消息；请在高频错误类别查看。</p>}</div>}}/>
 <Pagination style={{marginTop:12}} current={matchesRequest?offset/20+1:snapshot?.offset/20+1||1} pageSize={20} total={data?.total||0} showSizeChanger={false} onChange={p=>setOffset((p-1)*20)}/></div>
}
export function DailyAnomalies({ready,authError,onRetry,onAuthRevoked}){
 const [summary,setSummary]=useState(null),[date,setDate]=useState(''),[error,setError]=useState(null),[retry,setRetry]=useState(0),[selected,setSelected]=useState(null),[groupBy,setGroupBy]=useState('issue'),[developerId,setDeveloperId]=useState('');
 const generationRef=useRef(0),controllersRef=useRef(new Set());
 const currentGeneration=()=>generationRef.current;
 const trackController=controller=>{controllersRef.current.add(controller);return()=>controllersRef.current.delete(controller)};
 const abortAll=()=>{generationRef.current+=1;for(const controller of controllersRef.current)controller.abort('revoked');controllersRef.current.clear()};
 const revoke=reason=>{abortAll();setSummary(null);setDate('');setError({message:reason?.message||'认证已失效，请重新认证',status:reason?.status||403});setSelected(null);setDeveloperId('');setGroupBy('issue');onAuthRevoked?.(reason)};
 useEffect(()=>{if(!ready)return;const c=new AbortController(),generation=currentGeneration(),untrack=trackController(c);let active=true;const t=setTimeout(()=>c.abort('timeout'),15000),suffix=developerId?'?'+new URLSearchParams({developerId}):'';get('/api/anomalies/summary'+suffix,c.signal).then(x=>{if(!active||generation!==currentGeneration())return;setSummary(x.anomalies);setDate(old=>x.anomalies.dates.includes(old)?old:x.anomalies.dates.at(-1));setError(null)}).catch(e=>{if(!active||generation!==currentGeneration()||c.signal.reason==='revoked')return;if([401,403].includes(e.status))return revoke(e);setError({message:c.signal.reason==='timeout'?'异常摘要读取超时，请重试数据':e.message,status:e.status})}).finally(()=>{clearTimeout(t);untrack()});return()=>{active=false;clearTimeout(t);untrack();c.abort('obsolete')}},[retry,ready,developerId]);
 useEffect(()=>()=>abortAll(),[]);
 const rows=(summary?.groups||[]).filter(g=>g.date===date).sort((a,b)=>b.failureCount-a.failureCount);
 const appliedDeveloperId=summary?.developerFilter||'';
 const appliedDeveloper=appliedDeveloperId?(summary?.developers||[]).find(d=>d.id===appliedDeveloperId):null;
 return <main data-testid="daily-anomalies-page" style={{padding:16}}><div className="page-title"><div><Typography.Title level={3}>每日异常</Typography.Title><Typography.Text type="secondary">先看问题影响哪些包，再看每包指标和实际错误。缺数不当正常。</Typography.Text></div></div>
 <Space wrap style={{marginBottom:12}}><Select aria-label="分组方式" style={{width:150}} value={groupBy} options={[{value:'issue',label:'按问题分组'},{value:'developer',label:'按开发者分组'}]} onChange={v=>{setGroupBy(v);setDeveloperId('');setSelected(null)}}/><Select aria-label="异常日期" style={{width:180}} value={date||undefined} options={(summary?.dates||[]).map(value=>({value,label:value+' 完整自然日'}))} onChange={setDate}/>{groupBy==='developer'&&<Select aria-label="开发者筛选" allowClear style={{width:260}} value={developerId||undefined} placeholder="先选择开发者" options={(summary?.developers||[]).map(d=>({value:d.id,label:`${d.name} · ${d.id}`}))} onChange={v=>{setDeveloperId(v||'');setSelected(null)}}/>}{groupBy==='developer'&&appliedDeveloperId&&<span>当前已应用：{appliedDeveloper?.name||appliedDeveloperId} · {appliedDeveloperId}</span>}<Button onClick={()=>{setSelected(null);onRetry()}}>刷新已汇总结果</Button><span>注册 {summary?.registeredProjects??'—'} 项目 · 观测范围 {summary?.projectCount??'—'} 项目 · 映射去重 {summary?.packageCount??'—'} 包 · 包名未映射 {summary?.unmappedProjects??'—'} 项目</span></Space>
 {(error||authError)&&<Alert type="error" showIcon message={error?.message||authError?.message} action={authError?.status?<></>:authError?<Button onClick={onRetry}>重试读取</Button>:<Button onClick={()=>setRetry(x=>x+1)}>重试数据</Button>}/>}<Alert type={(summary?.stale||error)?'error':'info'} showIcon message={!summary&&error?'未获取数据 / 采集状态暂不可读取':(summary?.stale||error)?'结果陈旧或本轮失败；请勿视为当前结论':'后台每小时预汇总 · 北京时间09:00复查晚到数据'} description={<><div>检查时间：{summary?.checkedAt||'—'} · 下次计划：{summary?.nextCheckAt||'—'} · {summary?summary.checkKind||'采集类型未标注':'采集状态暂不可读取'}</div><div>{summary?.developerMapping?.status==='legacy_unsupported'?'该历史结果不支持开发者映射；请等待新采集。':summary?`开发者映射快照：${summary.developerMapping?.checkedAt||'—'}`:'未获取数据'} · {summary?.upstreamFinality||'无项目级最终完整性水位'}。</div></>}/>
 <Collapse style={{margin:'12px 0'}} items={[{key:'rules',label:'查看默认筛选口径（异常候选，非批准SLA）',children:<><p>分母≥{summary?.rules?.minSample??100}；TCP明确握手低于{summary?.rules?.tcpFloor??90}%或下降≥{summary?.rules?.dropPp??5}pp，广告加载终态低于{summary?.rules?.adLoadFloor??80}%或下降≥{summary?.rules?.dropPp??5}pp；广告浏览者比例、展示事件比及VPN比率无绝对目标，仅在两日样本均达标、下降≥{summary?.rules?.dropPp??5}pp且相对下降≥{summary?.rules?.relativeDropPct??20}%时列候选；错误事件≥{summary?.rules?.errorMinCount??100}且占全部加载失败≥{summary?.rules?.errorShareFloor??10}%。数据矛盾不受最小样本限制，单列为 data_anomaly。</p><p>广告浏览者比例=项目×北京时间自然日 ad_impression 去重 my_user_id / app_foreground 去重 my_user_id，不跨版本或国家求和。VPN连接成功率（终态）=结果日成功终态去重 connection_id / 结果日全部终态去重 connection_id；同日成功/发起只是非关联观察，跨日可超过100%，不等于失败率；connection_id、vpn_session_id 与用户转化不可混用。无基线不生成变化，异常基线排除普通下降比较；小样本不判健康。以上是临时工作筛选，不是统计显著性检验或已批准业务SLA。</p></>}]} />
 {groupBy==='developer'&&!developerId&&<Table data-testid="developer-groups" rowKey="id" size="small" pagination={false} dataSource={summary?.developers||[]} columns={[{title:'开发者',render:(_,r)=><Button type="link" onClick={()=>setDeveloperId(r.id)}>{r.name} · {r.id}</Button>},{title:'关联项目（当日去重）',render:(_,r)=>r.byDate?.[date]?.projectCount??0},{title:'受影响项目（当日去重）',render:(_,r)=>r.byDate?.[date]?.affectedProjects??0}]}/>} {(groupBy==='issue'||developerId)&&<Table data-testid="anomaly-groups" rowKey="category" size="small" loading={!summary&&!error&&!authError} pagination={false} scroll={{x:1200}} dataSource={rows} columns={[
 {title:'问题类别 / 指标',dataIndex:'label',width:300,render:(v,r)=><Button type="link" style={{whiteSpace:'normal',height:'auto',textAlign:'left'}} onClick={()=>setSelected({summary,group:r})}>{v}</Button>},
 {title:'受影响项目',dataIndex:'affectedProjects'},{title:'实际去重包数',dataIndex:'affectedPackages'},{title:'命中但包未映射',dataIndex:'unmappedAffectedProjects'},
 {title:'可计算 / 缺数',render:(_,r)=>`${r.coveredProjects} / ${r.missingProjects}`},{title:'小样本',dataIndex:'smallSampleProjects'},
 {title:'失败 / 差额 / 错误量',dataIndex:'failureCount',render:num},{title:'最大下降 / 中位变化',render:(_,r)=>`${pp(r.maxDropPp)} / ${pp(r.medianDeltaPp)}`},
 {title:'',render:(_,r)=><Button onClick={()=>setSelected({summary,group:r})}>查看全部项目</Button>}
 ]}/>}<p className="muted">项目和包总数均按当前筛选去重；多开发者项目会出现在各自组内，不能跨开发者组相加。失败指标也不能跨类别相加。</p>
 <Modal width="95%" open={!!selected} footer={null} destroyOnHidden title={selected?`${selected.group.date} · ${selected.group.label}`:''} onCancel={()=>setSelected(null)}>{selected&&<Details key={selected.summary.runId+selected.group.date+selected.group.category+(selected.summary.developerFilter||'')} summary={selected.summary} group={selected.group} developerId={selected.summary.developerFilter||''} onAuthRevoked={revoke} trackController={trackController} currentGeneration={currentGeneration}/>}</Modal>
 </main>
}
