"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type MetricDefinition = {
  key: string;
  nameZh: string;
  nameEn: string;
  category: string;
  description: string;
  source: string;
  freshness: string;
  eventName: string;
  filter: string;
  fields: string;
  formula: string;
  dedupe: string;
  trackingPosition: string;
  qualityRule: string;
};

export const metricDefinitions: MetricDefinition[] = [
  { key: "dau", nameZh: "日活跃用户数", nameEn: "DAU", category: "用户", description: "统计自然日内至少进入一次可交互前台的独立用户。", source: "Firebase → BigQuery → ADB", freshness: "T+0，通常延迟 5–15 分钟", eventName: "中台标准口径：jk_app_foreground；Firebase 对照口径：active_user", filter: "project_code、event_date、platform、country、app_version", fields: "my_user_id、session_id、foreground_reason、event_date、project_code", formula: "COUNT(DISTINCT my_user_id WHERE event_name='jk_app_foreground')", dedupe: "项目＋自然日＋my_user_id 去重", trackingPosition: "App 冷启动和每次从后台进入可交互前台时，由生命周期 Observer 上报", qualityRule: "my_user_id 缺失率必须为 0；与 Firebase active_user 差异建议不超过 3%" },
  { key: "page_uv", nameZh: "页面独立用户数", nameEn: "Page UV", category: "页面", description: "进入指定页面的独立用户数。", source: "Firebase 页面事件 → BigQuery → ADB", freshness: "T+0", eventName: "jk_screen_view", filter: "screen_name=当前页面；连接成功页示例 screen_name=vpn_connect_result", fields: "my_user_id、screen_name、previous_screen、screen_index、session_id、logged_at_ms", formula: "COUNT(DISTINCT my_user_id WHERE event_name='jk_screen_view' AND screen_name=当前页面)", dedupe: "项目＋页面＋统计周期＋my_user_id 去重", trackingPosition: "Navigation destination、Compose LaunchedEffect 或 Fragment 首次可见时上报；不可在预创建状态上报", qualityRule: "screen_name 为 P1；页面事件覆盖率建议 ≥99%" },
  { key: "page_arrival_rate", nameZh: "页面到达率", nameEn: "Page Arrival Rate", category: "页面", description: "活跃用户中实际到达指定页面的比例。", source: "Firebase 页面事件与 DAU 聚合", freshness: "T+0", eventName: "分子 jk_screen_view；分母 jk_app_foreground", filter: "同项目、同日期、同平台、同国家、同版本", fields: "my_user_id、screen_name、event_date", formula: "页面独立用户数（Page UV）÷ 日活跃用户数（DAU）× 100%", dedupe: "分子分母均按 my_user_id 独立去重", trackingPosition: "页面真正可见时上报 jk_screen_view；App 进入可交互前台时上报 jk_app_foreground", qualityRule: "分子与分母必须使用完全相同的筛选范围" },
  { key: "page_render_uv", nameZh: "页面渲染完成用户数", nameEn: "Render UV", category: "页面", description: "页面核心内容完成首屏渲染的独立用户数。V1.7 尚无明确的渲染完成动作枚举，需先扩展后才能作为正式指标。", source: "拟新增/扩展 Firebase 页面性能事件 → ADB", freshness: "接入后 T+0", eventName: "建议扩展：jk_core_action(action_name=screen_render_complete, action_result=success)", filter: "screen_name=当前页面", fields: "my_user_id、session_id、screen_name、action_name、action_result、duration_ms", formula: "COUNT(DISTINCT my_user_id WHERE action_name='screen_render_complete' AND action_result='success')", dedupe: "每用户每页面会话取首次渲染完成", trackingPosition: "首屏核心组件真正完成渲染后的 UI 回调中上报", qualityRule: "V1.7 未完整定义该动作；完成事件枚举与验收配置前，页面只能标记为演示指标" },
  { key: "page_render_rate", nameZh: "页面渲染完成率", nameEn: "Render Rate", category: "页面", description: "进入页面后成功完成首屏渲染的用户比例。", source: "Firebase 页面与扩展核心行为事件", freshness: "接入后 T+0", eventName: "jk_screen_view → jk_core_action(action_name=screen_render_complete)", filter: "同一 session_id、screen_name，限定 30 秒窗口", fields: "my_user_id、session_id、screen_name、action_name、action_result", formula: "页面渲染完成用户数 ÷ 页面独立用户数 × 100%", dedupe: "用户＋页面会话取首次到达和首次完成", trackingPosition: "页面可见上报 screen_view；首屏完成上报扩展 core_action", qualityRule: "V1.7 扩展项；关联率目标 ≥99%，超过窗口不补算" },
  { key: "element_exposure_uv", nameZh: "元素曝光独立用户数", nameEn: "Element Exposure UV", category: "页面", description: "指定按钮或核心元素真实可见的独立用户数。V1.7 只有 element_click，没有元素曝光事件。", source: "拟新增 Firebase 元素曝光事件 → ADB", freshness: "接入后 T+0", eventName: "建议新增：jk_element_exposure", filter: "screen_name=当前页面 AND element_name=指定元素", fields: "my_user_id、session_id、screen_name、element_name、visibility_reason", formula: "COUNT(DISTINCT my_user_id WHERE event_name='jk_element_exposure' AND element_name=指定元素)", dedupe: "同用户、同页面会话、同 element_name 只计首次曝光", trackingPosition: "元素进入可视区域并满足业务可见条件时上报；列表需做曝光去重", qualityRule: "V1.7 缺失项；新增事件、字段和验收配置前不可输出正式曝光率" },
  { key: "element_exposure_rate", nameZh: "核心元素曝光率", nameEn: "Element Exposure Rate", category: "页面", description: "完成页面渲染后看到核心元素的用户比例；依赖 V1.7 扩展的渲染完成与元素曝光信号。", source: "拟扩展 Firebase 页面事件", freshness: "接入后 T+0", eventName: "jk_element_exposure ÷ jk_core_action(screen_render_complete)", filter: "同 screen_name、同统计范围", fields: "my_user_id、session_id、screen_name、element_name", formula: "核心元素曝光独立用户数 ÷ 页面渲染完成用户数 × 100%", dedupe: "分子分母均按用户＋页面会话去重", trackingPosition: "渲染完成与元素真实可见两个时点分别上报", qualityRule: "V1.7 缺失项；补齐前不得用 screen_view 伪装元素曝光" },
  { key: "element_click_uv", nameZh: "元素点击独立用户数", nameEn: "Element Click UV", category: "页面", description: "至少点击一次指定元素的独立用户数。", source: "Firebase 页面点击事件", freshness: "T+0", eventName: "jk_element_click", filter: "screen_name=当前页面 AND element_name=指定元素", fields: "my_user_id、session_id、screen_name、element_name、action_name、ui_style", formula: "COUNT(DISTINCT my_user_id WHERE event_name='jk_element_click' AND element_name=指定元素)", dedupe: "同用户、同页面会话、同 element_name 取首次点击", trackingPosition: "统一 UI 点击代理层、Compose Modifier.clickable、View.OnClickListener 或导航点击封装", qualityRule: "element_name、action_name 为 P1；稳定英文枚举，不上传动态文案" },
  { key: "element_ctr", nameZh: "元素点击率", nameEn: "CTR", category: "页面", description: "看到指定元素的用户中发生点击的比例。", source: "Firebase 点击事件＋拟新增曝光事件", freshness: "曝光事件接入后 T+0", eventName: "jk_element_click ÷ jk_element_exposure", filter: "同 screen_name、element_name、统计周期与用户范围", fields: "my_user_id、screen_name、element_name", formula: "元素点击独立用户数 ÷ 元素曝光独立用户数 × 100%", dedupe: "分子分母均按用户去重，不能用点击次数除以曝光用户", trackingPosition: "曝光在元素真实可见时上报；点击在统一 UI 点击代理层上报", qualityRule: "V1.7 缺少分母事件；补齐曝光事件前只能用 Click UV / Page UV 作为替代指标并明确标注" },
  { key: "business_success_uv", nameZh: "业务成功独立用户数", nameEn: "Business Success UV", category: "产品", description: "完成当前页面核心业务目标的独立用户数。", source: "Firebase VPN 业务事件 → ADB", freshness: "T+0", eventName: "连接场景：jk_vpn_connection_result", filter: "vpn_status=connected/success；其他页面使用配置的 success_event_name", fields: "my_user_id、connection_id、vpn_status、trigger_type、node_region、duration_ms、error_code", formula: "COUNT(DISTINCT my_user_id WHERE vpn_status IN ('connected','success'))", dedupe: "每用户每 connection_id 只计一次成功", trackingPosition: "VPN SDK 返回连接成功且系统网络状态确认后上报", qualityRule: "connection_id、vpn_status 为链路必需；失败必须同时带 error_code" },
  { key: "business_success_rate", nameZh: "业务成功率", nameEn: "Business Success Rate", category: "产品", description: "点击核心操作后最终完成业务目标的用户比例。", source: "Firebase 点击＋VPN 结果事件", freshness: "T+0", eventName: "jk_element_click → jk_vpn_connection_result", filter: "同用户、同 session_id，限定业务完成窗口", fields: "my_user_id、session_id、element_name、action_name、connection_id、vpn_status", formula: "VPN 连接成功独立用户数 ÷ 连接按钮点击独立用户数 × 100%", dedupe: "按用户＋业务会话首次成功", trackingPosition: "点击时由 UI 代理层上报 element_click；SDK 结果回调上报 vpn_connection_result", qualityRule: "点击与结果的用户/会话关联率 ≥99%" },
  { key: "page_exit_rate", nameZh: "页面退出率", nameEn: "Page Exit Rate", category: "页面", description: "进入页面后离开且未完成配置目标动作的用户比例；页面离开与 App 进入后台分开统计。", source: "Firebase 页面、前后台与目标事件", freshness: "T+0", eventName: "jk_screen_exit；辅助 jk_app_background", filter: "screen_name=当前页面 AND 无目标成功事件", fields: "my_user_id、screen_name、next_screen、exit_action、screen_duration_ms、app_state、background_reason", formula: "无目标动作的页面离开独立用户数 ÷ 页面独立用户数 × 100%", dedupe: "用户＋页面会话只计一个最终退出结果", trackingPosition: "Navigation 页面离开回调上报 screen_exit；App 生命周期 Observer 单独上报 app_background", qualityRule: "禁止把 app_background 等同于 screen_exit；无法判断时按 app_state/unknown 分桶" },
  { key: "path_source_share", nameZh: "页面来源占比", nameEn: "Page Source Share", category: "页面", description: "进入当前页面的会话中来自指定上一页面的比例。", source: "Firebase 页面展示事件", freshness: "T+0", eventName: "jk_screen_view", filter: "screen_name=当前页面 AND previous_screen=指定来源页", fields: "session_id、screen_name、previous_screen、screen_index", formula: "来自指定 previous_screen 的页面会话数 ÷ 当前页面会话数 × 100%", dedupe: "session_id＋screen_index 去重", trackingPosition: "页面真正可见时记录稳定的 previous_screen", qualityRule: "previous_screen 为空或 unknown 单独统计；深链/通知首屏不得伪造来源页" },
  { key: "path_destination_share", nameZh: "页面去向占比", nameEn: "Page Destination Share", category: "页面", description: "离开当前页面的会话中前往指定下一页面的比例。", source: "Firebase 页面离开事件", freshness: "T+0", eventName: "jk_screen_exit", filter: "screen_name=当前页面 AND next_screen=指定去向页", fields: "session_id、screen_name、next_screen、exit_action、app_state", formula: "前往指定 next_screen 的退出会话数 ÷ 当前页面退出会话数 × 100%", dedupe: "每页面会话只取最终 next_screen", trackingPosition: "Navigation 确认页面离开和目标页面后上报 screen_exit", qualityRule: "App 后台不计为 next_screen；后台需使用 app_state/background_reason" },
  { key: "page_background_rate", nameZh: "页面停留期间 App 后台率", nameEn: "Page Background Rate", category: "页面", description: "当前页面可见期间整个 App 进入后台的页面会话比例。", source: "Firebase 页面与生命周期事件", freshness: "T+0", eventName: "jk_screen_view、jk_app_background", filter: "app_background.current_screen=当前页面", fields: "session_id、current_screen、background_reason、session_duration_ms、pending_ad_count", formula: "当前页面可见时进入后台的页面会话数 ÷ 当前页面会话数 × 100%", dedupe: "每页面会话最多计一次后台", trackingPosition: "App lifecycle Observer 进入后台时携带最后可见 current_screen", qualityRule: "不得由 screen_exit 推断 App 后台；background_reason 无法判断传 unknown" },
  { key: "opportunity_uv", nameZh: "广告机会独立用户数", nameEn: "Opportunity UV", category: "广告", description: "到达真实业务广告场景并生成广告机会的独立用户数。", source: "Firebase 广告机会事件 → ADB", freshness: "T+0", eventName: "jk_ad_opportunity", filter: "按 placement、ad_format、项目和版本筛选", fields: "my_user_id、opportunity_id、placement、ad_format、trigger_type、eligible、blocked_reason", formula: "COUNT(DISTINCT my_user_id WHERE event_name='jk_ad_opportunity')", dedupe: "用户数按 my_user_id；机会次数按 opportunity_id", trackingPosition: "真实业务展示场景到达时创建 opportunity_id 后立即上报；预加载不得创建机会", qualityRule: "opportunity_id、placement、ad_format 必传且唯一" },
  { key: "opportunity_coverage", nameZh: "广告机会覆盖率", nameEn: "Opportunity Coverage", category: "广告", description: "活跃用户中产生过真实广告机会的比例。", source: "Firebase 广告机会事件与 DAU", freshness: "T+0", eventName: "分子 jk_ad_opportunity；分母 jk_app_foreground", filter: "同项目、日期、平台、国家和版本", fields: "my_user_id、opportunity_id、event_date", formula: "广告机会独立用户数 ÷ 日活跃用户数 × 100%", dedupe: "分子分母按 my_user_id 独立去重", trackingPosition: "业务场景生成机会；生命周期记录前台活跃", qualityRule: "不能用广告机会次数除以 DAU" },
  { key: "request_uv", nameZh: "广告请求独立用户数", nameEn: "Request UV", category: "广告", description: "统计周期内至少发起一次预加载或实时广告请求的独立用户数，仅作为覆盖观察节点。", source: "Firebase 广告请求事件", freshness: "T+0", eventName: "jk_ad_request", filter: "is_preload IN (0,1)", fields: "my_user_id、request_id、is_preload、retry_index、opportunity_id、ad_unit_id", formula: "COUNT(DISTINCT my_user_id WHERE event_name='jk_ad_request')", dedupe: "预加载用户与实时请求用户求并集后去重", trackingPosition: "每次真实调用广告 SDK load 前创建 request_id 并上报", qualityRule: "Request UV 不是 Opportunity 的严格下一步；is_preload=1 时不得携带 opportunity_id" },
  { key: "request_count", nameZh: "广告请求次数", nameEn: "Ad Requests", category: "广告", description: "实际调用广告 SDK 发起 load 的请求总次数。", source: "Firebase T+0；AdMob T+3 对账", freshness: "Firebase T+0 / AdMob T+3", eventName: "Firebase：jk_ad_request；AdMob：AD_REQUESTS", filter: "按 request_type、placement、ad_format 拆分", fields: "event_id、request_id、request_type、placement、ad_unit_id", formula: "COUNT(DISTINCT request_id)", dedupe: "request_id 去重；每次重试必须创建新 request_id", trackingPosition: "广告 SDK load 调用前上报", qualityRule: "Firebase 与 AdMob 已结算日期请求差异建议 ≤3%" },
  { key: "match_rate", nameZh: "广告匹配率", nameEn: "Match Rate", category: "AdMob", description: "AdMob 请求中获得广告匹配的比例。", source: "AdMob Report API", freshness: "T+3 结算口径", eventName: "非客户端打点；AdMob 指标 MATCHED_REQUESTS、AD_REQUESTS", filter: "按 AdMob app、ad_unit、format、country、date", fields: "AD_REQUESTS、MATCHED_REQUESTS", formula: "MATCHED_REQUESTS ÷ AD_REQUESTS × 100%", dedupe: "使用 AdMob 聚合值，不与 Firebase 事件去重混算", trackingPosition: "无需客户端新增打点；由 AdMob SDK 与服务端报表产生", qualityRule: "只在同一结算日期、相同 AdMob 维度下计算" },
  { key: "show_rate", nameZh: "广告展示率", nameEn: "Show Rate", category: "AdMob", description: "已匹配广告中最终形成展示的比例。", source: "AdMob Report API", freshness: "T+3 结算口径", eventName: "非客户端打点；AdMob 指标 IMPRESSIONS、MATCHED_REQUESTS", filter: "按 app、ad_unit、format、country、date", fields: "IMPRESSIONS、MATCHED_REQUESTS", formula: "IMPRESSIONS ÷ MATCHED_REQUESTS × 100%", dedupe: "AdMob 聚合口径", trackingPosition: "无需客户端新增打点；Firebase jk_ad_show_attempt 用于当天技术诊断", qualityRule: "不得用 AV 代替 IMPRESSIONS" },
  { key: "show_attempt_uv", nameZh: "广告展示尝试独立用户数", nameEn: "Show Attempt UV", category: "广告", description: "至少执行一次广告 show 调用的独立用户数。", source: "Firebase 广告展示事件", freshness: "T+0", eventName: "jk_ad_show_attempt", filter: "按 placement、ad_format、app_state、activity_state", fields: "my_user_id、opportunity_id、request_id、ad_instance_id、loaded_to_show_ms、activity_state、app_state、trigger_type", formula: "COUNT(DISTINCT my_user_id WHERE event_name='jk_ad_show_attempt')", dedupe: "按 my_user_id 去重；事件效率另按 event_id 计数", trackingPosition: "缓存或实时广告对象校验通过、调用 show 前上报", qualityRule: "opportunity_id 与 ad_instance_id 关联率 ≥99%" },
  { key: "impression_count", nameZh: "广告展示次数", nameEn: "Impressions", category: "广告", description: "真实收到广告展示回调的事件总次数。", source: "Firebase T+0；AdMob T+3 最终对账", freshness: "Firebase T+0 / AdMob T+3", eventName: "Firebase：jk_ad_impression；AdMob：IMPRESSIONS", filter: "按 placement、ad_format、ad_unit_id、country", fields: "event_id、opportunity_id、ad_instance_id、placement、ad_unit_id", formula: "COUNT(DISTINCT event_id WHERE event_name='jk_ad_impression')", dedupe: "按 event_id 去重；不是独立用户数", trackingPosition: "广告 SDK Impression 回调中上报", qualityRule: "Firebase 与 AdMob 已结算日期差异建议 ≤3%" },
  { key: "av", nameZh: "广告展示独立用户数", nameEn: "AV", category: "广告", description: "统计周期内至少真实展示过一次广告的独立用户数，不是展示总次数。", source: "Firebase 广告展示事件", freshness: "T+0；AdMob 独立用户口径用于 T+3 对照", eventName: "jk_ad_impression", filter: "按项目、日期、平台、国家、版本", fields: "my_user_id、event_id、request_id、ad_instance_id、ad_source、mediation_adapter", formula: "COUNT(DISTINCT my_user_id WHERE event_name='jk_ad_impression')", dedupe: "项目＋统计周期＋my_user_id 去重", trackingPosition: "广告 SDK Impression 回调中上报", qualityRule: "my_user_id 必须稳定；Firebase 自动 ad_impression 不参与中台标准口径" },
  { key: "viewer_ratio", nameZh: "广告浏览者比例", nameEn: "AV / DAU", category: "广告", description: "活跃用户中真正看到过广告的用户比例。", source: "Firebase AV 与中台 DAU", freshness: "T+0 预估；T+3 对照", eventName: "分子 jk_ad_impression；分母 jk_app_foreground", filter: "同项目、日期、平台、国家和版本", fields: "my_user_id、event_date", formula: "广告展示独立用户数（AV）÷ 日活跃用户数（DAU）× 100%", dedupe: "分子分母分别按 my_user_id 去重", trackingPosition: "Impression 回调与 App 进入前台时分别上报", qualityRule: "AV 与 DAU 必须来自相同用户标识和时区" },
  { key: "impressions_per_viewer", nameZh: "人均广告展示次数", nameEn: "Impressions per Viewer", category: "广告", description: "每个广告展示用户平均产生的展示次数，用于识别展示是否集中在少数用户。", source: "Firebase 广告展示事件", freshness: "T+0", eventName: "jk_ad_impression", filter: "同项目与统计周期", fields: "event_id、my_user_id", formula: "广告展示次数（Impression Count）÷ 广告展示独立用户数（AV）", dedupe: "分子 event_id 去重；分母 my_user_id 去重", trackingPosition: "广告 SDK Impression 回调中上报一次", qualityRule: "必须同时展示 AV，避免高人均掩盖低覆盖" },
  { key: "revenue", nameZh: "广告收入", nameEn: "Ad Revenue", category: "收入", description: "广告 Paid 回调产生的收入金额。", source: "Firebase T+0 预估；AdMob T+3 最终结算", freshness: "T+0 / T+3", eventName: "Firebase：jk_ad_paid_event；AdMob：ESTIMATED_EARNINGS", filter: "currency_code 统一换算；按项目和日期", fields: "value_micros、currency_code、ad_instance_id、precision_type", formula: "SUM(value_micros) ÷ 1,000,000；跨币种先按汇率统一", dedupe: "event_id 去重；同 ad_instance_id 重复回调进入质量告警", trackingPosition: "广告 SDK OnPaidEvent 回调中上报", qualityRule: "value_micros 使用 Int64；currency_code 必传；最终收入以 AdMob 结算为准" },
  { key: "revenue_share", nameZh: "页面广告收入占比", nameEn: "Page Revenue Share", category: "收入", description: "当前页面或广告场景贡献的广告收入占项目总广告收入的比例。", source: "Firebase T+0 预估；AdMob T+3 结算", freshness: "T+0 / T+3", eventName: "jk_ad_paid_event；AdMob ESTIMATED_EARNINGS", filter: "同项目、日期、币种，按 placement/screen_name 归属", fields: "value_micros、currency_code、placement、screen_name、ad_instance_id", formula: "当前页面归属广告收入 ÷ 项目总广告收入 × 100%", dedupe: "event_id 去重；页面归属使用 placement 映射表", trackingPosition: "Paid 回调沿用 ad_instance_id 的 placement 与页面 Context", qualityRule: "页面归属率应 ≥99%；最终占比使用同一 AdMob 结算日期" },
  { key: "arpdau", nameZh: "每活跃用户收入", nameEn: "ARPDAU", category: "收入", description: "每个日活跃用户平均贡献的广告收入。", source: "AdMob 结算收入＋Firebase/中台 DAU", freshness: "T+3 最终口径", eventName: "收入来自 AdMob；DAU 来自 jk_app_foreground", filter: "同项目、同自然日、同币种", fields: "revenue、my_user_id、event_date", formula: "广告收入 ÷ 日活跃用户数（DAU）", dedupe: "DAU 按 my_user_id 去重；收入按结算值", trackingPosition: "无需新增事件；复用 Paid Event 与前台事件", qualityRule: "禁止用不同日期或不同时区的收入与 DAU 相除" },
  { key: "ecpm", nameZh: "千次展示收入", nameEn: "eCPM", category: "收入", description: "每一千次广告展示产生的收入。", source: "AdMob Report API", freshness: "T+3 结算口径", eventName: "非客户端打点；ESTIMATED_EARNINGS、IMPRESSIONS", filter: "按 app、ad_unit、format、country、date", fields: "ESTIMATED_EARNINGS、IMPRESSIONS", formula: "广告收入 ÷ 广告展示次数 × 1,000", dedupe: "使用 AdMob 聚合值", trackingPosition: "无需客户端新增打点", qualityRule: "展示次数为 Impression Count，不是 AV" },
  { key: "render_p50", nameZh: "页面渲染耗时中位数", nameEn: "Render P50", category: "性能", description: "50% 页面渲染样本不超过该耗时；V1.7 需要先扩展 screen_render_complete 动作。", source: "扩展 Firebase 核心行为事件 → ADB 分位数聚合", freshness: "接入后 T+0", eventName: "jk_core_action(action_name=screen_render_complete)", filter: "action_result='success' AND duration_ms BETWEEN 0 AND 60000", fields: "duration_ms、screen_name、device_model、app_version", formula: "APPROX_PERCENTILE(duration_ms, 0.50)", dedupe: "每页面会话保留首个有效渲染完成事件", trackingPosition: "页面首屏渲染完成时记录 monotonic elapsed time", qualityRule: "V1.7 扩展项；duration_ms 超范围进入隔离，使用单调时钟" },
  { key: "render_p95", nameZh: "页面渲染耗时 P95", nameEn: "Render P95", category: "性能", description: "95% 页面渲染样本不超过该耗时，用于识别长尾卡顿；V1.7 需要扩展动作。", source: "扩展 Firebase 核心行为事件 → ADB 分位数聚合", freshness: "接入后 T+0", eventName: "jk_core_action(action_name=screen_render_complete)", filter: "action_result='success' AND duration_ms BETWEEN 0 AND 60000", fields: "duration_ms、screen_name、network_type、device_model、app_version", formula: "APPROX_PERCENTILE(duration_ms, 0.95)", dedupe: "每页面会话保留首个有效样本", trackingPosition: "页面首屏渲染完成时上报 duration_ms", qualityRule: "V1.7 扩展项；按版本、设备和网络拆解，不能用平均值替代 P95" },
  { key: "api_latency", nameZh: "接口耗时", nameEn: "API Latency", category: "性能", description: "页面关键业务接口从发起到完成的耗时。", source: "Firebase 接口质量事件", freshness: "T+0", eventName: "jk_api_request_result", filter: "api_name=页面关键接口", fields: "api_name、duration_ms、http_status、success、error_code", formula: "默认展示 P50；诊断同时查看 P95/P99", dedupe: "request_trace_id 去重", trackingPosition: "网络拦截器收到最终成功或失败结果时上报", qualityRule: "重试分别记录 retry_index；超时也必须上报结果" },
  { key: "page_error_rate", nameZh: "页面错误率", nameEn: "Page Error Rate", category: "性能", description: "页面会话中发生渲染或关键业务错误的比例。", source: "Firebase 核心行为与接口质量事件", freshness: "T+0", eventName: "jk_core_action(success=0) 或 jk_api_request_result(success=0)", filter: "screen_name=当前页面", fields: "session_id、screen_name、success、error_code、error_domain", formula: "发生错误的页面会话数 ÷ 页面会话数 × 100%", dedupe: "同 session_id 同 error_code 只计一次", trackingPosition: "渲染异常捕获、接口最终失败或业务异常回调处上报", qualityRule: "error_message 截断至 100 字符；以 error_code 聚合" },
  { key: "white_screen_rate", nameZh: "页面白屏率", nameEn: "White Screen Rate", category: "性能", description: "页面进入后在阈值窗口内没有完成首屏渲染的会话比例。", source: "ADB 服务端派生", freshness: "扩展事件接入后 T+0", eventName: "jk_screen_view 后无 jk_core_action(screen_render_complete)", filter: "同 session_id、screen_name，阈值默认 5 秒", fields: "session_id、screen_name、logged_at_ms、action_name、app_state", formula: "超时未渲染完成的页面会话数 ÷ 页面会话数 × 100%", dedupe: "页面会话级；服务端派生，客户端不直接传 white_screen=true", trackingPosition: "客户端准确上报 screen_view 与扩展的 screen_render_complete", qualityRule: "V1.7 扩展项；App 后台、页面正常退出需排除，Unknown 单独统计" },
  { key: "p0_completeness", nameZh: "P0 参数完整率", nameEn: "P0 Parameter Completeness", category: "数据质量", description: "已触发事件中所有 P0 必填参数均合法的比例。", source: "ADB 质量引擎", freshness: "T+0", eventName: "适用于 V1.7 allowlist 中全部事件", filter: "按 schema_version、event_name、app_version", fields: "event_id、schema_version、P0字段集合、validation_errors", formula: "P0 参数全部合法的事件数 ÷ 应校验事件数 × 100%", dedupe: "event_id 去重后校验", trackingPosition: "统一事件序列化层写入公共字段；业务 Provider 写入专属字段", qualityRule: "发布门禁要求 100%" },
  { key: "event_pass_rate", nameZh: "事件验收通过率", nameEn: "Event Pass Rate", category: "数据质量", description: "配置快照要求的事件中，事件、参数和关联链全部通过的比例。", source: "打点验收中心", freshness: "当前验收 Run", eventName: "以 Run 引用的 snapshot_id 事件集合为准", filter: "project_code、app_version、device_id、run_id", fields: "expected_event_id、received_status、parameter_status、chain_status", formula: "通过事件数 ÷ 配置要求验证事件数 × 100%", dedupe: "每个 expected_event_id 只产生一个最终结论", trackingPosition: "按测试操作指引触发对应业务和广告事件", qualityRule: "P0 事件通过率必须 100%；未执行场景不计失败" },
  { key: "unknown_event_rate", nameZh: "未知事件率", nameEn: "Unknown Event Rate", category: "数据质量", description: "收到但不在当前版本 allowlist 中的事件比例。", source: "ADB 入库边界质量引擎", freshness: "T+0", eventName: "event_name NOT IN schema allowlist", filter: "按 schema_version、project_code、app_version", fields: "event_name、schema_version、event_id", formula: "未知事件数 ÷ 收到事件总数 × 100%", dedupe: "event_id 去重", trackingPosition: "客户端统一事件上报入口；事件名必须来自发布规范", qualityRule: "目标 <0.5%；未知事件进入隔离区但不得静默丢弃" },
  { key: "quarantine_count", nameZh: "隔离事件数", nameEn: "Quarantined Events", category: "数据质量", description: "因 event_id 缺失、未知事件、类型非法或关键字段错误进入隔离表的事件数。", source: "ADB 质量隔离表", freshness: "T+0", eventName: "全部接收事件", filter: "quality_status='QUARANTINED'", fields: "event_id、event_name、error_code、raw_oss_path、received_at", formula: "COUNT(*) WHERE quality_status='QUARANTINED'", dedupe: "可用 event_id 去重；缺 ID 事件按 payload_hash 辅助去重", trackingPosition: "客户端统一序列化与发送层；服务端入库边界校验", qualityRule: "隔离事件必须可检索、可回放、不可静默删除" },
  { key: "reason_coverage", nameZh: "流失原因分类覆盖率", nameEn: "Reason Coverage", category: "诊断", description: "流失样本中能够被明确规则分类的比例。", source: "ADB 流失诊断规则引擎", freshness: "T+0 聚合", eventName: "由目标区间前后事件链服务端派生", filter: "选定 from_step、to_step、诊断窗口", fields: "my_user_id、logged_at_ms、reason_code、opportunity_id、request_id", formula: "已分类流失样本数 ÷ 全部流失样本数 × 100%", dedupe: "每个流失样本只保留一个最高优先级 reason_code", trackingPosition: "客户端准确上报页面离开、App 后台、blocked_reason 与广告链事件", qualityRule: "目标 ≥99%" },
  { key: "unknown_reason_rate", nameZh: "未知流失原因率", nameEn: "Unknown Reason Rate", category: "诊断", description: "流失样本中无法被现有规则解释的比例。", source: "ADB 流失诊断规则引擎", freshness: "T+0 聚合", eventName: "服务端派生 reason_code=UNKNOWN", filter: "选定诊断区间与窗口", fields: "reason_code、last_event_name、next_event_name、event_time", formula: "UNKNOWN 流失样本数 ÷ 全部流失样本数 × 100%", dedupe: "流失样本级", trackingPosition: "补齐 screen_exit、app_background、blocked_reason 及关键关联 ID", qualityRule: "目标 <1%；超过阈值不得输出高可信根因" },
  { key: "eligibility_rate", nameZh: "广告资格通过率", nameEn: "Eligibility Rate", category: "广告", description: "执行广告资格检查的用户中符合展示策略的比例。", source: "Firebase 广告资格事件", freshness: "T+0", eventName: "jk_ad_eligibility_check", filter: "按 placement、ad_format、版本、订阅与隐私状态", fields: "my_user_id、eligible、blocked_reason、placement、ad_format、is_subscriber、consent_status", formula: "COUNT(DISTINCT my_user_id WHERE eligible=1) ÷ COUNT(DISTINCT my_user_id with eligibility_check) × 100%", dedupe: "用户＋placement＋资格决策窗口取最后一次结果", trackingPosition: "请求/load 前完成订阅、频控、国家、版本、配置、SDK 与网络检查后上报", qualityRule: "eligible=0 时 blocked_reason 条件必填；unknown 占比目标 <1%" },
  { key: "load_success_rate", nameZh: "广告加载成功率", nameEn: "Load Success Rate", category: "广告", description: "真实广告请求最终获得可用广告对象的比例。", source: "Firebase 广告请求与加载结果事件", freshness: "T+0", eventName: "jk_ad_load_success ÷ jk_ad_request", filter: "按 is_preload、ad_format、ad_unit_id、国家和版本", fields: "request_id、is_preload、retry_index、load_duration_ms、error_category、ad_source、mediation_adapter", formula: "COUNT(DISTINCT success.request_id) ÷ COUNT(DISTINCT request.request_id) × 100%", dedupe: "request_id 一次请求只保留一个终态", trackingPosition: "load 前上报 request；SDK load 成功/失败回调上报唯一终态", qualityRule: "每个 request_id 必须有且只有一个 load_success 或 load_failed 终态" },
  { key: "cache_hit_rate", nameZh: "广告缓存命中率", nameEn: "Cache Hit Rate", category: "广告", description: "真实广告机会检查缓存时成功取到可用广告对象的比例。", source: "Firebase 广告缓存事件", freshness: "T+0", eventName: "jk_ad_cache_hit、jk_ad_cache_miss", filter: "按 placement、ad_format、cache_scope、版本", fields: "opportunity_id、request_id、ad_instance_id、cache_age_ms、miss_reason", formula: "COUNT(DISTINCT hit.opportunity_id) ÷ COUNT(DISTINCT opportunity_id with hit or miss) × 100%", dedupe: "每个 opportunity_id 仅保留一次缓存检查结论", trackingPosition: "真实机会消费缓存时上报 hit 或 miss；预加载生产阶段不计命中", qualityRule: "hit+miss 机会覆盖率目标 ≥99%；同一机会不得同时命中和未命中" },
  { key: "user_left_block_rate", nameZh: "用户离页阻止率", nameEn: "User-left Block Rate", category: "广告", description: "广告已加载但因用户离开当前页面未展示的比例。", source: "Firebase 广告展示阻止事件", freshness: "T+0", eventName: "jk_ad_show_blocked", filter: "blocked_reason='user_left_page'", fields: "ad_instance_id、request_id、from_screen、to_screen、loaded_to_block_ms、app_state", formula: "user_left_page 阻止实例数 ÷ 加载成功实例数 × 100%", dedupe: "ad_instance_id 只保留一个终态", trackingPosition: "广告加载后、展示前发生页面离开时上报；App 仍在前台", qualityRule: "不得与 app_background 合并；from_screen、to_screen 可得时必传" },
  { key: "background_block_rate", nameZh: "App 后台阻止率", nameEn: "Background Block Rate", category: "广告", description: "广告已加载但因整个 App 进入后台未展示的比例。", source: "Firebase 广告阻止＋生命周期事件", freshness: "T+0", eventName: "jk_ad_show_blocked(blocked_reason=app_background)；jk_app_background", filter: "加载成功后、展示前", fields: "ad_instance_id、blocked_reason、app_state、background_reason、pending_ad_count", formula: "app_background 阻止实例数 ÷ 加载成功实例数 × 100%", dedupe: "ad_instance_id 终态去重", trackingPosition: "App lifecycle Observer 确认进入后台，且存在待展示实例时上报", qualityRule: "页面离开不等于 App 后台；两个原因必须互斥" },
  { key: "ad_expiry_rate", nameZh: "广告缓存过期率", nameEn: "Ad Expiry Rate", category: "广告", description: "加载成功的广告对象中因超过有效期未被消费的比例。", source: "Firebase 缓存过期事件", freshness: "T+0", eventName: "jk_ad_cache_expired", filter: "按 ad_format、placement、cache_scope、版本", fields: "request_id、ad_instance_id、cache_age_ms、estimated_expire_at", formula: "过期 ad_instance_id 数 ÷ 进入缓存的 ad_instance_id 数 × 100%", dedupe: "ad_instance_id 只计一次过期终态", trackingPosition: "缓存读取、定时清理或对象失效检测确认过期时上报", qualityRule: "过期、丢弃、展示/关闭终态必须互斥；长期升高需调整 TTL 与预加载时机" },
  { key: "paid_callback_coverage", nameZh: "Paid 回传覆盖率", nameEn: "Paid Callback Coverage", category: "收入", description: "广告展示后收到收益回调的覆盖比例。", source: "Firebase Impression 与 Paid Event", freshness: "T+0 诊断", eventName: "jk_ad_paid_event ÷ jk_ad_impression", filter: "同 ad_instance_id、按广告源/版本拆解", fields: "ad_instance_id、event_id、value_micros、currency_code、precision_type、ad_source", formula: "有 Paid Event 的去重 ad_instance_id ÷ Impression 去重 ad_instance_id × 100%", dedupe: "ad_instance_id 关联；重复 Paid 回调按 event_id 去重并告警", trackingPosition: "广告 SDK OnPaidEvent 回调中立即上报", qualityRule: "按 SDK 支持范围设目标；value_micros 为 Int64，currency_code 条件必填" },
  { key: "vpn_connection_rate", nameZh: "VPN 连接成功率", nameEn: "VPN Connection Success Rate", category: "VPN", description: "VPN 连接尝试中最终成功建立隧道的比例。", source: "Firebase VPN 连接结果事件", freshness: "T+0", eventName: "jk_vpn_connection_result", filter: "按 node_region、trigger_type、网络、版本、国家", fields: "connection_id、vpn_status、trigger_type、node_region、duration_ms、error_code、network_type", formula: "成功 connection_id 数 ÷ 全部终态 connection_id 数 × 100%", dedupe: "connection_id 只保留一个最终结果", trackingPosition: "VPN SDK/系统网络确认连接成功、失败或取消形成终态时上报", qualityRule: "失败时 error_code 条件必填；按节点、网络和版本下钻" },
  { key: "ack_rate", nameZh: "事件 ACK 成功率", nameEn: "Telemetry ACK Rate", category: "数据质量", description: "发送到自有中台的事件中被服务端接受的比例。Firebase 首期无中台 ACK 时不适用。", source: "自有中台上报健康事件", freshness: "T+0", eventName: "jk_telemetry_batch_send、jk_telemetry_backend_ack", filter: "仅中台直传/必达链路", fields: "batch_id、event_count、accepted_count、rejected_count、ack_duration_ms", formula: "SUM(accepted_count) ÷ SUM(event_count) × 100%", dedupe: "batch_id 去重，重试批次按原始 batch_id 合并", trackingPosition: "发送批次前记录 send；收到服务端 ACK 后记录 backend_ack", qualityRule: "目标 ≥99.5%；Firebase 直传链路不得伪造 ACK" },
  { key: "dau_gap_rate", nameZh: "Firebase 与中台 DAU 偏差率", nameEn: "DAU Gap Rate", category: "数据质量", description: "Firebase 活跃用户与中台实际收到前台事件用户之间的相对差异。", source: "Firebase active_user＋ADB 前台事件", freshness: "T+0 预估，T+1 稳定", eventName: "Firebase active_user；中台 jk_app_foreground", filter: "同项目、日期、平台、时区、版本", fields: "firebase_active_users、my_user_id、project_code、event_date", formula: "ABS(Firebase DAU－中台 DAU) ÷ Firebase DAU × 100%", dedupe: "两端分别按各自稳定用户 ID 去重", trackingPosition: "App 进入前台上报 app_foreground；Firebase active_user 自动产生", qualityRule: "<3% 正常；3%–5% 关注；>5% 告警并按国家/版本/网络下钻" },
  { key: "telemetry_user_coverage", nameZh: "上报成功用户覆盖率", nameEn: "Telemetry User Coverage", category: "数据质量", description: "活跃用户中至少有一个批次被自有中台成功接收的用户比例。", source: "ADB 上报健康事件＋DAU", freshness: "T+0", eventName: "jk_telemetry_backend_ack、jk_app_foreground", filter: "仅中台直传/必达链路", fields: "my_user_id、batch_id、accepted_count、event_date、network_type", formula: "有 accepted_count>0 的独立用户数 ÷ 中台 DAU × 100%", dedupe: "自然日＋my_user_id 去重", trackingPosition: "服务端 ACK 后记录 backend_ack；Firebase 首期不适用", qualityRule: "目标 ≥99%；按国家、版本、网络拆解" },
  { key: "event_drop_rate", nameZh: "事件丢弃率", nameEn: "Event Drop Rate", category: "数据质量", description: "客户端生成后因队列容量、格式非法或不可恢复错误被丢弃的事件比例。", source: "客户端上报队列健康事件", freshness: "T+0", eventName: "V1.7 指标表引用 telemetry_event_dropped，但事件总表尚未完整定义，需补充", filter: "仅中台直传/必达链路", fields: "drop_reason、dropped_count、generated_count、queue_size、oldest_event_age_ms", formula: "SUM(dropped_count) ÷ SUM(generated_count) × 100%", dedupe: "按队列统计窗口聚合，不重复累加累计值", trackingPosition: "本地队列确认不可恢复丢弃时记录", qualityRule: "目标 <0.1%；V1.7 事件定义补齐前不得作为发布门禁" },
  { key: "receive_latency_p95", nameZh: "事件接收延迟 P95", nameEn: "Receive Latency P95", category: "数据质量", description: "事件发生到服务端接收之间的长尾延迟。", source: "ADB 原始事件表", freshness: "T+0", eventName: "全部已接收事件；服务端派生", filter: "排除明确标记的离线补报后另行展示", fields: "logged_at_ms、server_receive_time、event_id、is_backfill", formula: "P95(server_receive_time－logged_at_ms)", dedupe: "event_id 去重", trackingPosition: "客户端统一序列化层记录 logged_at_ms；服务端写入 receive_time", qualityRule: "在线事件目标 <10 分钟；补报单独分桶" },
  { key: "first_open_users", nameZh: "首次打开用户数", nameEn: "First-open Users", category: "用户", description: "安装后首次启动并成功上报首开事件的独立用户数。", source: "Firebase 首开事件", freshness: "T+0", eventName: "jk_app_first_open", filter: "按 install_source、is_reinstall、国家、版本", fields: "my_user_id、install_time、is_reinstall、install_source", formula: "COUNT(DISTINCT my_user_id WHERE event_name='jk_app_first_open')", dedupe: "每次安装只计一次；重装分组展示", trackingPosition: "Application 启动且本地 first_open_sent=false 时上报", qualityRule: "需与商店安装或 MMP 对账；首开重复率目标 <0.1%" },
  { key: "session_count", nameZh: "前台会话数", nameEn: "Sessions", category: "用户", description: "统计周期内进入可交互前台的独立会话数量。", source: "Firebase 生命周期事件", freshness: "T+0", eventName: "jk_app_foreground", filter: "按项目、日期、国家、版本", fields: "session_id、session_index、foreground_reason、launch_type", formula: "COUNT(DISTINCT session_id)", dedupe: "session_id 去重", trackingPosition: "冷启动和每次后台回前台时创建/恢复会话并上报", qualityRule: "session_id 缺失率为 0；会话超时规则全项目统一" },
  { key: "avg_session_duration", nameZh: "平均前台会话时长", nameEn: "Average Session Duration", category: "用户", description: "每次前台会话平均持续时间。", source: "Firebase 生命周期与心跳事件", freshness: "T+0", eventName: "jk_app_background；辅助 jk_session_heartbeat", filter: "排除异常负数和超过 24 小时样本", fields: "session_id、session_duration_ms、foreground_duration_ms、background_reason", formula: "SUM(每会话最终前台时长) ÷ COUNT(DISTINCT session_id)", dedupe: "session_id 只取最终 background 时长；进程被杀时用最后 heartbeat 兜底", trackingPosition: "App 进入后台时记录 session_duration_ms；长会话定时 heartbeat", qualityRule: "短会话需按 <10s/<30s 分桶；heartbeat 兜底样本单独标记" },
  { key: "first_screen_exit_rate", nameZh: "首屏退出率", nameEn: "First-screen Exit Rate", category: "用户", description: "活跃用户进入首个页面后未到达下一页面或核心动作即退出/进入后台的比例。", source: "Firebase 页面与生命周期事件", freshness: "T+0", eventName: "jk_screen_view、jk_screen_exit、jk_app_background", filter: "screen_index=1 且无后续页面/目标动作", fields: "my_user_id、session_id、screen_index、exit_action、next_screen、app_state、background_reason", formula: "首屏后直接退出或后台的独立用户数 ÷ DAU × 100%", dedupe: "每用户每日首次会话取首屏最终状态", trackingPosition: "页面可见、页面离开和 App 后台三个时点分别上报", qualityRule: "页面离开与 App 后台分开统计；按渠道、版本、国家下钻" },
  { key: "request_user_coverage", nameZh: "广告请求用户覆盖率", nameEn: "Request User Coverage", category: "广告", description: "活跃用户中至少发起一次预加载或实时广告请求的比例；不是 Opportunity 的严格转化率。", source: "Firebase Request UV＋DAU", freshness: "T+0", eventName: "jk_ad_request、jk_app_foreground", filter: "同项目、日期、平台、国家、版本", fields: "my_user_id、request_id、is_preload、opportunity_id", formula: "广告请求独立用户数（Request UV）÷ DAU × 100%", dedupe: "按 my_user_id 去重；预加载和实时请求取并集", trackingPosition: "每次 SDK load 前上报 request；App 前台上报 DAU", qualityRule: "缓存命中可不产生实时请求；不得把 Request UV 当作 Opportunity 的线性下一步" },
  { key: "load_success_user_rate", nameZh: "广告加载成功用户率", nameEn: "Load-success User Rate", category: "广告", description: "请求用户中至少成功加载一个广告对象的用户比例。", source: "Firebase 请求与加载事件", freshness: "T+0", eventName: "jk_ad_load_success、jk_ad_request", filter: "按 is_preload、广告格式、广告位、版本", fields: "my_user_id、request_id、ad_instance_id、load_duration_ms", formula: "有 load_success 的独立用户数 ÷ Request UV × 100%", dedupe: "分子分母均按 my_user_id 去重", trackingPosition: "SDK load 成功回调创建 ad_instance_id 后上报", qualityRule: "与 AdMob 匹配率不等价；请求终态关联率目标 ≥99%" },
  { key: "show_user_coverage", nameZh: "广告展示尝试用户覆盖率", nameEn: "Show-attempt User Coverage", category: "广告", description: "有可用广告对象的用户中实际调用过 show 的比例。", source: "Firebase Load Success 与 Show Attempt", freshness: "T+0", eventName: "jk_ad_show_attempt、jk_ad_load_success", filter: "按缓存/实时履约分支和广告格式", fields: "my_user_id、ad_instance_id、request_id、loaded_to_show_ms、app_state", formula: "Show Attempt UV ÷ Load Success UV × 100%", dedupe: "分子分母按 my_user_id 去重", trackingPosition: "广告对象校验通过、调用 show 前上报", qualityRule: "低时下钻 user_left_page、app_background、ad_expired、no_presenter" },
  { key: "paid_user_ratio", nameZh: "付费广告用户比例", nameEn: "Paid Ad User Ratio", category: "收入", description: "活跃用户中至少产生一次 Paid Event 的用户比例。", source: "Firebase Paid Event＋DAU", freshness: "T+0 预估", eventName: "jk_ad_paid_event、jk_app_foreground", filter: "同项目、日期、平台、国家、版本", fields: "my_user_id、ad_instance_id、value_micros、currency_code", formula: "有 Paid Event 的独立用户数 ÷ DAU × 100%", dedupe: "按 my_user_id 去重；重复 Paid 回调不重复计用户", trackingPosition: "SDK OnPaidEvent 回调中上报", qualityRule: "必须与 AV/DAU 同屏；SDK 不支持 Paid 的流量需排除" },
  { key: "opportunity_request_rate", nameZh: "机会后实时请求率", nameEn: "Opportunity-to-Realtime Request Rate", category: "广告", description: "缓存未命中的真实广告机会中发起实时请求的比例；预加载请求不进入分子。", source: "Firebase 缓存未命中与广告请求事件", freshness: "T+0", eventName: "jk_ad_cache_miss → jk_ad_request", filter: "is_preload=0 且 opportunity_id 非空", fields: "opportunity_id、request_id、is_preload、miss_reason", formula: "有 realtime request 的 cache_miss opportunity_id 数 ÷ cache_miss opportunity_id 数 × 100%", dedupe: "opportunity_id 去重；重试不增加分子", trackingPosition: "缓存未命中后、真实调用实时 load 前上报 request", qualityRule: "比 V1.7 原 ad_request/ad_opportunity 更准确；缓存命中机会不应被判定流失" },
  { key: "show_success_rate", nameZh: "广告展示尝试成功率", nameEn: "Show Success Rate", category: "广告", description: "调用 show 后最终收到真实 Impression 回调的比例。", source: "Firebase Show Attempt 与 Impression", freshness: "T+0", eventName: "jk_ad_impression ÷ jk_ad_show_attempt", filter: "按 ad_format、placement、Activity 状态、版本", fields: "ad_instance_id、opportunity_id、activity_state、app_state、show_to_impression_ms", formula: "有 Impression 的去重 ad_instance_id 数 ÷ Show Attempt 去重 ad_instance_id 数 × 100%", dedupe: "ad_instance_id 去重", trackingPosition: "调用 show 前上报 attempt；SDK Impression 回调上报 impression", qualityRule: "通常目标 ≥95%；低时查 show_failed、页面切换和回调超时" },
  { key: "end_to_end_show_rate", nameZh: "请求到展示端到端率", nameEn: "Request-to-Impression Rate", category: "广告", description: "每次广告请求最终形成真实展示的比例；预加载与实时请求必须分开。", source: "Firebase Request 与 Impression 关联链", freshness: "T+0", eventName: "jk_ad_request → jk_ad_impression", filter: "按 is_preload、ad_format、ad_unit_id、国家", fields: "request_id、ad_instance_id、event_id、is_preload", formula: "形成 Impression 的去重 request_id 数 ÷ 去重 request_id 数 × 100%", dedupe: "request_id 去重；一个预加载实例只关联一次最终展示", trackingPosition: "请求、加载和展示回调使用同一 requestContext/instanceContext", qualityRule: "缓存对象跨机会消费时必须保留 request_id 与 ad_instance_id 关联" },
  { key: "request_api_gap_rate", nameZh: "客户端与 AdMob 请求差异率", nameEn: "Client/AdMob Request Gap", category: "对账", description: "客户端记录的广告 SDK load 次数与 AdMob 报表请求数之间的差异。", source: "Firebase jk_ad_request＋AdMob Report API", freshness: "T+3 结算口径", eventName: "jk_ad_request；AdMob AD_REQUESTS", filter: "同 app、ad_unit、format、country、settled_date", fields: "request_id、ad_unit_id、ad_format、AD_REQUESTS", formula: "ABS(Client Requests－AdMob AD_REQUESTS) ÷ AdMob AD_REQUESTS × 100%", dedupe: "客户端按 request_id；AdMob 使用平台聚合", trackingPosition: "真实 SDK load 前上报 request；AdMob 无需额外打点", qualityRule: "差异建议 ≤3%；大时查重复埋点、SDK 未调用或映射错误" },
  { key: "requests_per_dau", nameZh: "DAU 人均广告请求次数", nameEn: "Requests per DAU", category: "广告强度", description: "每个活跃用户平均产生的广告请求次数。", source: "Firebase Request＋DAU", freshness: "T+0", eventName: "jk_ad_request、jk_app_foreground", filter: "同项目和自然日", fields: "request_id、my_user_id、is_preload", formula: "COUNT(DISTINCT request_id) ÷ DAU", dedupe: "请求按 request_id；DAU 按 my_user_id", trackingPosition: "SDK load 前上报 request；App 前台上报 foreground", qualityRule: "需与 Request UV、人均请求同时看，避免少数用户拉高均值" },
  { key: "requests_per_requester", nameZh: "请求用户人均请求次数", nameEn: "Requests per Requester", category: "广告强度", description: "实际请求广告的用户平均请求次数。", source: "Firebase 广告请求事件", freshness: "T+0", eventName: "jk_ad_request", filter: "按 is_preload、广告格式、广告位", fields: "request_id、my_user_id、retry_index、is_preload", formula: "COUNT(DISTINCT request_id) ÷ Request UV", dedupe: "分子 request_id，分母 my_user_id", trackingPosition: "每次真实 load 前上报；重试新建 request_id", qualityRule: "异常升高时查重试、过度预加载和重复触发" },
  { key: "impressions_per_dau", nameZh: "DAU 人均广告展示次数", nameEn: "Impressions per DAU", category: "广告强度", description: "全部活跃用户平均产生的广告展示次数。", source: "Firebase Impression＋DAU", freshness: "T+0", eventName: "jk_ad_impression、jk_app_foreground", filter: "同项目、日期、平台、国家、版本", fields: "event_id、my_user_id", formula: "广告展示次数 ÷ DAU", dedupe: "展示按 event_id；DAU 按 my_user_id", trackingPosition: "Impression 回调和前台生命周期分别上报", qualityRule: "ARPDAU 主要驱动之一；必须与 AV/DAU 和 Impression/AV 同屏" },
  { key: "zero_impression_share", nameZh: "0 次展示用户占比", nameEn: "Zero-impression User Share", category: "广告强度", description: "活跃用户中当天没有产生任何广告展示的用户比例。", source: "ADB 用户日活与 Impression 左连接", freshness: "T+0", eventName: "jk_app_foreground LEFT JOIN jk_ad_impression", filter: "同项目和自然日", fields: "my_user_id、event_date、event_id", formula: "无 Impression 的 DAU 用户数 ÷ DAU × 100%", dedupe: "用户日粒度", trackingPosition: "无需新增事件；复用前台和 Impression 事件", qualityRule: "必须同时展示 0/1/2–3/4–5/6–10/10+ 展示次数分桶" },
  { key: "ad_ctr", nameZh: "广告点击率", nameEn: "Ad CTR", category: "收入", description: "广告展示后产生点击的比例。", source: "Firebase 广告点击与展示事件；AdMob 结算对照", freshness: "T+0 / T+3", eventName: "jk_ad_click ÷ jk_ad_impression", filter: "按 ad_format、placement、ad_source、国家", fields: "event_id、request_id、ad_instance_id", formula: "广告点击次数 ÷ 广告展示次数 × 100%", dedupe: "event_id 去重；同一点击回调只记一次", trackingPosition: "广告 SDK Click 回调中上报 jk_ad_click；不得使用 Firebase 保留名 ad_click", qualityRule: "异常高需检查重复回调、误触和无效流量" },
  { key: "vpn_opportunity_rate", nameZh: "连接成功后广告机会率", nameEn: "Post-connect Opportunity Rate", category: "VPN", description: "VPN 连接成功用户中随后产生真实广告机会的比例。", source: "Firebase VPN 与 Opportunity 关联链", freshness: "T+0", eventName: "jk_vpn_connection_result → jk_ad_opportunity", filter: "同用户/connection_id 后 30 分钟内、指定 placement", fields: "my_user_id、connection_id、vpn_status、opportunity_id、placement", formula: "连接成功后产生 Opportunity 的独立用户数 ÷ VPN 连接成功独立用户数 × 100%", dedupe: "用户＋connection_id 首个 Opportunity", trackingPosition: "连接终态回调上报 VPN 结果；连接成功页面真正可见时创建 Opportunity", qualityRule: "低时优先查业务接入点、页面离开、App 后台和配置阻止" },
  { key: "vpn_viewer_rate", nameZh: "连接成功后广告浏览率", nameEn: "Post-connect Viewer Rate", category: "VPN", description: "VPN 连接成功用户中随后真实看到广告的比例。", source: "Firebase VPN 与 Impression 关联链", freshness: "T+0", eventName: "jk_vpn_connection_result → jk_ad_impression", filter: "连接后限定窗口和 placement", fields: "my_user_id、connection_id、opportunity_id、ad_instance_id、placement", formula: "连接成功后有 Impression 的独立用户数 ÷ VPN 连接成功独立用户数 × 100%", dedupe: "按用户＋connection_id 去重", trackingPosition: "连接成功终态、机会和 Impression 回调需保持上下文关联", qualityRule: "需拆分机会覆盖和机会后展示效率，不能只看首尾" },
  { key: "ip_before_capture_rate", nameZh: "连接前 IP 采集成功率", nameEn: "IP-before Capture Rate", category: "VPN/IP", description: "VPN 建连尝试中成功保存连接前公网 IP 上下文的比例。", source: "自有中台 vpnSessionContext", freshness: "T+0", eventName: "非 Firebase 明文参数；连接前 IP 回显接口", filter: "按国家、网络、版本、接口错误码", fields: "vpn_session_id、ip_before_status、ip_before_hash、country_before", formula: "ip_before_status='success' 会话数 ÷ VPN 建连尝试会话数 × 100%", dedupe: "vpn_session_id 去重", trackingPosition: "每次 connect 前调用自有 IP 回显接口并保存 vpnSessionContext", qualityRule: "Firebase 不传明文 IP；失败需记录 status/error，不能传空字符串" },
  { key: "ip_after_capture_rate", nameZh: "连接后 IP 采集成功率", nameEn: "IP-after Capture Rate", category: "VPN/IP", description: "VPN 连接成功会话中成功保存隧道出口 IP 的比例。", source: "自有中台 vpnSessionContext", freshness: "T+0", eventName: "隧道成功后 IP 回显接口", filter: "按节点、协议、网络、版本", fields: "vpn_session_id、ip_after_status、ip_after_hash、country_after", formula: "ip_after_status='success' 会话数 ÷ VPN 连接成功会话数 × 100%", dedupe: "vpn_session_id 去重", trackingPosition: "隧道确认成功后通过 VPN 路由调用 IP 回显接口", qualityRule: "低时检查隧道路由、DNS、超时与接口可达性" },
  { key: "ad_request_after_ip_rate", nameZh: "广告请求携带连接后 IP 上下文率", nameEn: "Ad Request after-IP Context Rate", category: "VPN/IP", description: "已连接广告请求中能关联有效连接后 IP 上下文的比例。", source: "Firebase Request＋自有中台 VPN 上下文关联", freshness: "T+0", eventName: "jk_ad_request；ip_after_connect 不明文传 Firebase", filter: "vpn_active=1 且广告请求发生在有效 VPN 会话内", fields: "vpn_session_id、request_id、ip_after_status、ip_after_hash、logged_at_ms", formula: "关联有效 after-IP Context 的已连接 request_id 数 ÷ 已连接 request_id 数 × 100%", dedupe: "request_id 去重", trackingPosition: "广告拉取事件保存 vpn_session_id/Context 关联；明文 IP 只进自有中台", qualityRule: "低时查 Context 未保存、错绑、过期或 IP 接口失败" },
  { key: "ip_change_rate", nameZh: "VPN 前后公网 IP 变化率", nameEn: "IP Change Rate", category: "VPN/IP", description: "连接前后 IP 均成功采集的会话中公网出口发生变化的比例。", source: "自有中台 vpnSessionContext", freshness: "T+0", eventName: "服务端派生", filter: "before/after status 均为 success", fields: "vpn_session_id、ip_before_hash、ip_after_hash", formula: "ip_before_hash<>ip_after_hash 的会话数 ÷ 双端采集成功会话数 × 100%", dedupe: "vpn_session_id 去重", trackingPosition: "客户端采集上下文；服务端比较 hash，不在 Firebase 暴露明文", qualityRule: "长期不变需检查分流、绕行或出口探测未走隧道" },
  { key: "country_change_rate", nameZh: "VPN 出口国家变化率", nameEn: "Exit Country Change Rate", category: "VPN/IP", description: "可比较 VPN 会话中连接后出口国家与连接前国家不同的比例。", source: "自有中台 GeoIP 派生", freshness: "T+0", eventName: "服务端派生", filter: "before/after GeoIP 均可用", fields: "vpn_session_id、country_before、country_after、node_region", formula: "country_before<>country_after 的会话数 ÷ 可比较会话数 × 100%", dedupe: "vpn_session_id 去重", trackingPosition: "无需额外 Firebase 参数；服务端对 before/after IP 做统一 GeoIP", qualityRule: "需与用户选择节点国家一致性一起看；GeoIP 库版本必须记录" },
  { key: "firebase_ip_join_rate", nameZh: "Firebase 广告请求与 IP 上下文关联率", nameEn: "Firebase/IP Join Rate", category: "VPN/IP", description: "Firebase 广告请求能通过关联键匹配自有中台 VPN/IP 上下文的比例。", source: "BigQuery Firebase 事件＋ADB VPN Context", freshness: "T+0", eventName: "jk_ad_request JOIN vpnSessionContext", filter: "vpn_active=1 的目标请求", fields: "request_id、vpn_session_id、my_user_id、logged_at_ms、ip_after_status", formula: "成功关联 VPN/IP Context 的 request_id 数 ÷ 目标 request_id 数 × 100%", dedupe: "request_id 去重；时间窗口仅作兜底，不替代关联键", trackingPosition: "广告请求上报稳定关联键；自有中台保存 vpn_session_id", qualityRule: "目标 ≥99%；低时查关联键缺失或中台接口失败" },
  { key: "product_completion_rate", nameZh: "产品主路径完成率", nameEn: "Product Completion Rate", category: "产品", description: "进入配置产品漏斗的用户中严格按顺序完成最终业务目标的比例。", source: "ADB 可配置漏斗引擎", freshness: "T+0", eventName: "由项目发布的 funnel_snapshot 定义入口与终点事件", filter: "同项目、版本、国家、平台和配置窗口", fields: "metric_key、snapshot_id、my_user_id、session_id、from_event、to_event、logged_at_ms", formula: "严格顺序到达最终步骤的独立用户数 ÷ 到达入口步骤的独立用户数 × 100%", dedupe: "每用户每漏斗会话只取首次到达", trackingPosition: "按项目配置的 screen_view、element_click、core_action 或业务结果事件上报", qualityRule: "页面、报表和告警必须引用同一 snapshot_id；漏斗版本变化不得覆盖历史" },
  { key: "funnel_conversion_rate", nameZh: "漏斗步骤转化率", nameEn: "Funnel Step Conversion Rate", category: "诊断", description: "选定起点与终点之间按配置顺序到达终点的比例。", source: "ADB 动态漏斗引擎", freshness: "T+0", eventName: "由 from_metric_key、to_metric_key 对应事件产生", filter: "诊断窗口、顺序模式和用户/事件口径由快照固定", fields: "from_step、to_step、snapshot_id、my_user_id、event_id、logged_at_ms", formula: "到达 to_step 的去重样本数 ÷ 到达 from_step 的去重样本数 × 100%", dedupe: "用户模式按 my_user_id；事件模式按业务关联 ID", trackingPosition: "复用两端标准事件；不新增所谓 conversion 事件", qualityRule: "Request UV 等非严格观察节点必须明确标注，不能直接认定为技术流失" },
  { key: "opportunity_fulfillment_rate", nameZh: "广告机会履约率", nameEn: "Opportunity Fulfillment Rate", category: "广告", description: "真实广告机会中最终进入展示尝试的比例，合并缓存命中和实时请求两条分支。", source: "Firebase Opportunity 与 Show Attempt", freshness: "T+0", eventName: "jk_ad_opportunity → jk_ad_show_attempt", filter: "同 placement、ad_format、版本与履约窗口", fields: "opportunity_id、ad_instance_id、request_id、cache_status", formula: "有 Show Attempt 的去重 opportunity_id 数 ÷ 去重 opportunity_id 数 × 100%", dedupe: "opportunity_id 去重", trackingPosition: "真实业务场景创建 Opportunity；实际调用 show 前上报 Show Attempt", qualityRule: "缓存命中可跳过新请求；不得用 Request 作为统一分母" },
  { key: "preload_success_rate", nameZh: "广告预加载成功率", nameEn: "Preload Success Rate", category: "广告缓存", description: "预加载请求中成功生成可缓存广告实例的比例。", source: "Firebase Request 与 Load Success", freshness: "T+0", eventName: "jk_ad_request → jk_ad_load_success", filter: "is_preload=1", fields: "request_id、is_preload、ad_instance_id、load_duration_ms、error_category", formula: "成功 load 的预加载 request_id 数 ÷ 预加载 request_id 数 × 100%", dedupe: "request_id 唯一终态", trackingPosition: "预加载真实 load 前上报 request；成功回调创建实例后上报 load_success", qualityRule: "预加载不得生成 opportunity_id；成功不等于最终被消费" },
  { key: "cache_waste_rate", nameZh: "广告缓存浪费率", nameEn: "Cache Waste Rate", category: "广告缓存", description: "进入缓存但因过期或丢弃而未形成展示的广告实例比例。", source: "Firebase 缓存建立与终态事件", freshness: "T+0", eventName: "jk_ad_cache_expired、jk_ad_cache_discard ÷ jk_ad_cache_put", filter: "按 ad_format、cache_scope、版本", fields: "ad_instance_id、request_id、discard_reason、cache_age_ms、cache_size_after", formula: "(过期实例数＋丢弃实例数) ÷ 进入缓存实例数 × 100%", dedupe: "ad_instance_id 只保留一个终态", trackingPosition: "缓存 put、expired、discard 回调中上报；展示/关闭实例不计浪费", qualityRule: "异常高时调 TTL、缓存容量和预加载时机；终态互斥率必须 100%" },
  { key: "chain_completeness", nameZh: "事件关联链完整率", nameEn: "Event Chain Completeness", category: "数据质量", description: "要求关联的事件链中关键 ID、时序和终态全部合法的比例。", source: "ADB 链路质量引擎", freshness: "T+0", eventName: "V1.7 广告与业务标准事件", filter: "按 snapshot_id、app_version、链路类型", fields: "event_id、connection_id、opportunity_id、request_id、ad_instance_id、logged_at_ms", formula: "关键 ID 和顺序全部合法的链路数 ÷ 应校验链路数 × 100%", dedupe: "按链路主键去重", trackingPosition: "各业务 Context 生成并保存关联 ID 至对象终态", qualityRule: "P0 发布门禁要求 100%；失败链必须可下钻到具体缺失事件/字段" },
  { key: "api_success_rate", nameZh: "接口成功率", nameEn: "API Success Rate", category: "性能", description: "页面或业务关键接口最终成功返回的请求比例。", source: "Firebase 接口质量事件", freshness: "T+0", eventName: "jk_api_request_result", filter: "按 api_name、国家、版本、网络和 error_stage", fields: "api_name、api_path、success、http_code、duration_ms、error_stage、error_code", formula: "success=1 的去重请求数 ÷ 接口请求总数 × 100%", dedupe: "request_trace_id 去重；重试按 retry_index 拆分", trackingPosition: "网络拦截器收到最终成功、失败或超时结果时上报", qualityRule: "失败和超时必须上报；error_message 清洗并截断至 100 字符" },
  { key: "d1_retention", nameZh: "次日留存率", nameEn: "D1 Retention", category: "用户", description: "首日新增用户在次日再次进入前台的比例。", source: "Firebase 用户 Cohort → ADB", freshness: "T+1 稳定", eventName: "jk_app_first_open、jk_app_foreground", filter: "install_date=D0，active_date=D0+1", fields: "my_user_id、install_time、is_reinstall、event_date", formula: "D1 回访新增用户数 ÷ D0 新增用户数 × 100%", dedupe: "用户＋安装批次去重", trackingPosition: "首次启动上报 first_open；每次进入前台上报 app_foreground", qualityRule: "统一项目时区；重装用户按 is_reinstall 口径单独分析" },
  { key: "roas", nameZh: "广告投入回报率", nameEn: "ROAS", category: "经营", description: "广告收入相对于投放消耗的比例。", source: "AdMob 收入＋投放平台消耗", freshness: "以共同结算日期为准", eventName: "非单一客户端打点；收入与消耗由外部 API 拉取", filter: "同项目、日期、币种和投放归属", fields: "ad_revenue、ad_spend、currency_code", formula: "广告收入 ÷ 投放消耗 × 100%", dedupe: "按项目与投放账户映射聚合", trackingPosition: "无需客户端新增打点；归因维度依赖归因 SDK", qualityRule: "收入和消耗必须使用同一结算窗口与汇率" },
  { key: "profit", nameZh: "预估利润", nameEn: "Estimated Profit", category: "经营", description: "当前口径下收入扣除投放消耗及配置成本后的预估利润。", source: "AdMob、投放平台与成本配置", freshness: "结算日期口径", eventName: "非客户端打点", filter: "同项目、日期、币种", fields: "revenue、spend、configured_cost", formula: "总收入－投放消耗－配置成本", dedupe: "项目日聚合", trackingPosition: "无需客户端新增打点", qualityRule: "必须展示是否包含服务器、渠道和税费成本" },
];

const aliasRules: Array<[RegExp, string]> = [
  [/白屏率/i, "white_screen_rate"], [/渲染.*P95|Render P95/i, "render_p95"], [/渲染.*P50|Render P50/i, "render_p50"], [/接口耗时|API.*耗时/i, "api_latency"], [/页面错误率|错误率/i, "page_error_rate"],
  [/页面.*UV|Page UV|进入页面/i, "page_uv"], [/到达率/i, "page_arrival_rate"], [/渲染完成率/i, "page_render_rate"], [/渲染完成用户|Render UV/i, "page_render_uv"], [/核心.*曝光率|元素曝光率/i, "element_exposure_rate"], [/曝光.*UV|元素曝光/i, "element_exposure_uv"], [/点击.*UV/i, "element_click_uv"], [/主按钮.*CTR|元素.*CTR|元素点击率/i, "element_ctr"], [/业务成功率/i, "business_success_rate"], [/业务成功|后续成功/i, "business_success_uv"], [/页面退出率/i, "page_exit_rate"], [/页面来源|来源页/i, "path_source_share"], [/页面去向|去向页/i, "path_destination_share"], [/页面.*后台率|App.*后台率/i, "page_background_rate"],
  [/Opportunity.*覆盖|机会覆盖/i, "opportunity_coverage"], [/Opportunity UV|广告机会独立用户|^Opportunity$/i, "opportunity_uv"], [/Request UV|广告请求独立用户/i, "request_uv"], [/广告请求次数|^Ad Requests$|^Request$/i, "request_count"], [/匹配率|Match Rate/i, "match_rate"], [/AdMob.*展示率|^展示率$|^Show Rate$/i, "show_rate"], [/Show Attempt UV|广告展示尝试独立用户/i, "show_attempt_uv"], [/浏览者人均展示|人均广告展示次数|Impression.*AV/i, "impressions_per_viewer"], [/浏览者比例|AV\s*\/\s*DAU/i, "viewer_ratio"], [/独立用户.*AV|广告展示独立用户|\bAV\b/i, "av"], [/Impression|展示总次数|广告展示次数/i, "impression_count"],
  [/DAU.*偏差|DAU Gap/i, "dau_gap_rate"], [/上报成功用户覆盖/i, "telemetry_user_coverage"], [/事件丢弃率/i, "event_drop_rate"], [/接收延迟.*P95/i, "receive_latency_p95"], [/首开用户|首次打开用户/i, "first_open_users"], [/会话数|Sessions/i, "session_count"], [/平均.*会话时长/i, "avg_session_duration"], [/首屏退出率/i, "first_screen_exit_rate"],
  [/资格.*率|Eligibility/i, "eligibility_rate"], [/请求用户覆盖率/i, "request_user_coverage"], [/加载成功用户率/i, "load_success_user_rate"], [/Show.*用户覆盖|展示尝试用户覆盖/i, "show_user_coverage"], [/付费广告用户比例/i, "paid_user_ratio"], [/机会后实时请求率|Opportunity-to-Realtime/i, "opportunity_request_rate"], [/加载成功率|Load Success/i, "load_success_rate"], [/缓存命中率|Cache Hit/i, "cache_hit_rate"], [/展示尝试成功率/i, "show_success_rate"], [/端到端展示率|Request-to-Impression/i, "end_to_end_show_rate"], [/离页阻止/i, "user_left_block_rate"], [/后台阻止/i, "background_block_rate"], [/缓存过期率|广告过期率/i, "ad_expiry_rate"], [/客户端.*AdMob.*请求|请求.*差异/i, "request_api_gap_rate"],
  [/DAU.*人均请求/i, "requests_per_dau"], [/请求用户.*人均请求/i, "requests_per_requester"], [/DAU.*人均展示/i, "impressions_per_dau"], [/0次展示/i, "zero_impression_share"], [/广告点击率|Ad CTR|^CTR$/i, "ad_ctr"], [/Paid.*覆盖|回传覆盖/i, "paid_callback_coverage"], [/VPN.*连接成功率/i, "vpn_connection_rate"], [/连接后广告机会率/i, "vpn_opportunity_rate"], [/连接后广告浏览率/i, "vpn_viewer_rate"], [/连接前.*IP.*采集/i, "ip_before_capture_rate"], [/连接后.*IP.*采集/i, "ip_after_capture_rate"], [/广告请求.*IP.*上下文/i, "ad_request_after_ip_rate"], [/IP.*变化率/i, "ip_change_rate"], [/出口国家变化率/i, "country_change_rate"], [/Firebase.*IP.*关联/i, "firebase_ip_join_rate"], [/ACK.*率/i, "ack_rate"],
  [/产品.*完成率/i, "product_completion_rate"], [/漏斗.*转化率|当前转化/i, "funnel_conversion_rate"], [/机会履约率/i, "opportunity_fulfillment_rate"], [/预加载成功率/i, "preload_success_rate"], [/缓存浪费率/i, "cache_waste_rate"], [/关联链完整率|事件链可关联率/i, "chain_completeness"], [/接口成功率/i, "api_success_rate"],
  [/ARPDAU/i, "arpdau"], [/eCPM/i, "ecpm"], [/收入占比/i, "revenue_share"], [/收入|Revenue/i, "revenue"], [/P0.*参数.*完整率/i, "p0_completeness"], [/事件通过率|验收通过率/i, "event_pass_rate"], [/未知事件率/i, "unknown_event_rate"], [/隔离事件/i, "quarantine_count"], [/原因分类覆盖率/i, "reason_coverage"], [/Unknown率|未知流失/i, "unknown_reason_rate"], [/D1|次日留存/i, "d1_retention"], [/ROAS/i, "roas"], [/利润/i, "profit"], [/DAU|日活跃用户/i, "dau"],
];

export function resolveMetricDefinition(input: string): MetricDefinition {
  const normalized = input.trim();
  const exact = metricDefinitions.find((item) => item.key === normalized || item.nameZh === normalized || item.nameEn === normalized);
  if (exact) return exact;
  const alias = aliasRules.find(([pattern]) => pattern.test(normalized));
  if (alias) return metricDefinitions.find((item) => item.key === alias[1])!;
  return {
    key: `generic:${normalized}`,
    nameZh: normalized,
    nameEn: "Operational Metric",
    category: "运营与系统",
    description: "当前指标为后台运营或系统状态统计，按页面筛选条件聚合。",
    source: "ADB 业务表或控制表",
    freshness: "以页面数据水位为准",
    eventName: "非固定客户端打点；由对应业务表、任务表或配置表聚合",
    filter: "project_code、date、status 及当前页面筛选条件",
    fields: "以指标详情页展示的来源表字段为准",
    formula: `COUNT / SUM 当前筛选范围内与“${normalized}”对应的有效记录`,
    dedupe: "按对应业务主键去重",
    trackingPosition: "如为客户端指标需在正式指标注册表补充事件；系统状态无需客户端打点",
    qualityRule: "指标上线前必须在指标注册表明确来源表、字段、公式、负责人和数据水位",
  };
}

export const MetricInspectContext = createContext<(metric: string) => void>(() => undefined);

export function MetricLabel({ metric, children, className = "" }: { metric: string; children: React.ReactNode; className?: string }) {
  const inspect = useContext(MetricInspectContext);
  const definition = resolveMetricDefinition(metric);
  const open = (event: React.MouseEvent | React.KeyboardEvent) => {
    event.preventDefault();
    event.stopPropagation();
    inspect(metric);
  };
  return <span className={`metric-label-with-info ${className}`}><span>{children}</span><span className="metric-info-trigger" role="button" tabIndex={0} aria-label={`查看${definition.nameZh}的来源字段、公式和打点位置`} title="查看来源字段、计算公式和打点位置" onClick={open} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") open(event); }}>i</span></span>;
}

export function MetricDictionaryDrawer({ open, selectedMetric, onSelect, onClose }: { open: boolean; selectedMetric: string; onSelect: (metric: string) => void; onClose: () => void }) {
  const [search, setSearch] = useState("");
  const selected = resolveMetricDefinition(selectedMetric || "dau");
  const visible = useMemo(() => {
    const keyword = search.trim().toLowerCase();
    if (!keyword) return metricDefinitions;
    return metricDefinitions.filter((item) => [item.nameZh, item.nameEn, item.category, item.eventName, item.fields].join(" ").toLowerCase().includes(keyword));
  }, [search]);
  useEffect(() => {
    if (!open) return;
    const previousOverflow = document.body.style.overflow;
    const closeOnEscape = (event: KeyboardEvent) => event.key === "Escape" && onClose();
    document.body.style.overflow = "hidden";
    window.addEventListener("keydown", closeOnEscape);
    return () => {
      document.body.style.overflow = previousOverflow;
      window.removeEventListener("keydown", closeOnEscape);
    };
  }, [onClose, open]);
  if (!open) return null;
  return <div className="metric-drawer-backdrop" onMouseDown={onClose}>
    <aside className="metric-drawer" role="dialog" aria-modal="true" aria-label="指标口径字典" onMouseDown={(event) => event.stopPropagation()}>
      <header><div><span>指标治理 · V1.7</span><h2>指标口径字典</h2><p>所有指标统一使用中文名称，并明确来源、公式、字段、去重与打点位置。</p></div><button onClick={onClose} aria-label="关闭指标口径字典">×</button></header>
      <div className="metric-drawer-layout">
        <nav><label>搜索指标、事件或字段<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="例如：页面 UV、jk_ad_impression" /></label><div className="metric-dictionary-count">共 {visible.length} 个标准指标</div><div className="metric-dictionary-list">{visible.map((item) => <button key={item.key} className={selected.key === item.key ? "active" : ""} onClick={() => onSelect(item.key)}><span>{item.category}</span><strong>{item.nameZh}</strong><small>{item.nameEn}</small></button>)}</div></nav>
        <main>
          <div className="metric-definition-title"><div><span>{selected.category}</span><h3>{selected.nameZh}</h3><p>{selected.nameEn}</p></div><em>{selected.freshness}</em></div>
          <p className="metric-definition-description">{selected.description}</p>
          <section className="metric-formula-card"><span>统一计算公式</span><code>{selected.formula}</code></section>
          <dl>
            <div><dt>数据来源</dt><dd>{selected.source}</dd></div>
            <div><dt>来源事件 / API 指标</dt><dd><code>{selected.eventName}</code></dd></div>
            <div><dt>筛选条件</dt><dd>{selected.filter}</dd></div>
            <div><dt>使用字段</dt><dd><code>{selected.fields}</code></dd></div>
            <div><dt>去重口径</dt><dd>{selected.dedupe}</dd></div>
            <div><dt>客户端打点位置</dt><dd>{selected.trackingPosition}</dd></div>
            <div><dt>质量与验收规则</dt><dd>{selected.qualityRule}</dd></div>
          </dl>
          <div className="metric-drawer-note"><strong>实施规则</strong><p>页面、导出、告警和接口必须引用同一个 metric_key。Firebase 自动广告事件只做对照；中台广告标准指标只读 jk_ 自定义链路事件，避免重复计算。</p></div>
        </main>
      </div>
    </aside>
  </div>;
}
